import type { ChickenPackId, ChickenYardId } from "@/lib/chicken-meta";

export type ChickenDare = {
  id: string;
  n: number;
  yard: ChickenYardId;
  pack: ChickenPackId;
  name: string;
  body: string;
};

const OUT: ChickenPackId[] = ["talk", "move", "shop", "park", "dine", "ride"];

function packFor(n: number): ChickenPackId {
  if (n <= 25) return "talk";
  if (n <= 50) return "move";
  if (n <= 75) return "shop";
  if (n <= 100) return "park";
  if (n <= 125) return "dine";
  if (n <= 150) return "ride";
  if (n <= 175) return "kitchen";
  if (n <= 200) return "couch";
  if (n <= 225) return "bed";
  if (n <= 250) return "bath";
  if (n <= 275) return "chores";
  return "banter";
}

function yardFor(pack: ChickenPackId): ChickenYardId {
  return (OUT as string[]).includes(pack) ? "out" : "home";
}

const RAW: [string, string][] = [
  ["The Serious Negotiator", "Try to haggle or ask for a loyalty discount on a single $3 coffee or snack."],
  ["The Whisper Order", "Place your entire order at a fast-food counter or café in an intense, secretive whisper."],
  ["The Rhyming Customer", "Speak only in rhyming sentences to the next store employee who asks if you need help."],
  ["The Dramatic Farewell", "Say goodbye to a total stranger in a store like you’re off to fight in an 18th-century war. “May the tides bring me back to you!”"],
  ["The Overly Enthusiastic Compliment", "Walk up to a stranger and enthusiastically compliment something super mundane — shoelaces, a cereal brand, their choice of bananas."],
  ["The Phantom Friend", "Wave passionately at a stranger, walk over, say “Oh wait, you aren’t Barnaby!”, and walk away smoothly."],
  ["The Reverse Question", "When a server asks “How are you today?”, look genuinely concerned and ask “More importantly, how are YOU holding up?”"],
  ["The Antique Appraisal", "Ask a supermarket worker what year a specific jar of pickles was produced, and if it’s a good vintage."],
  ["The Formal Apology", "Apologize profusely to a mannequin after accidentally bumping into it."],
  ["The Secret Agent Handshake", "Attempt an elaborate, 5-step secret handshake with the next person who hands you a receipt."],
  ["The Dramatic Reading", "Read a fast-food menu out loud in the style of a Shakespearean tragedy."],
  ["The Over-Explainer", "Give a 30-second detailed history on why you are buying a specific item at the checkout."],
  ["The Posh Accent", "Ask where the restroom is using the most aristocratic, high-society voice you can muster."],
  ["The Fortune Teller", "Look at the cashier’s palm when they hand you your change and say “Ah, a prosperous Tuesday awaits you.”"],
  ["The Mystery Warning", "Lean over to someone looking at vegetables and whisper “The carrots are particularly untrustworthy today.”"],
  ["The Monologue", "Ask for directions to a shop, then pause and deliver a 15-second dramatic internal monologue out loud."],
  ["The Celebrity Mistake", "Walk up to a stranger, gasp, ask “Are you the lead singer of Smash Mouth?”, then look disappointed when they say no."],
  ["The Timed Silent Nod", "Give the next 3 people you pass in a hallway a very slow, intense, cinematic nod without smiling."],
  ["The Extreme Gratitude", "Thank a barista so intensely for your drink that you look like you’re going to cry tears of joy."],
  ["The Slow-Motion Order", "Order a coffee where every word takes 3 seconds to pronounce."],
  ["The Alien Observer", "Ask a store employee how a basic item (like a banana) works and what human function it serves."],
  ["The High-Five Request", "Ask a cashier if they will give you a high-five before you tap your card to pay."],
  ["The Unnecessary Conference", "Call your partner over from another aisle in a panicked voice just to show them a slightly odd-shaped potato."],
  ["The Time Traveler Check", "Ask a passerby “Quick! What year is it?!” and look visibly relieved when they answer."],
  ["The Dramatic Exit", "Walk out of a clothing shop bowing repeatedly to the store employees until you pass through the doors."],
  ["The Invisible Tightrope", "Walk across a pedestrian crossing as if you are balancing on a high wire over a volcano."],
  ["The Sideways Shuffle", "Crab-walk or side-step down an entire aisle in a home-improvement or grocery store."],
  ["The Stealth Mission", "Move from pillar to pillar outside a shopping centre using tactical military crouches."],
  ["The Synchronized March", "March in perfect military lockstep behind your partner for 50 paces."],
  ["The Floor Inspection", "Bend down and inspect a completely normal floor tile with extreme scrutiny for 15 seconds."],
  ["The Heroic Pose", "Stand at the top of an escalator or stairs in a classic superhero pose until you reach the other end."],
  ["The Slow Jump", "Attempt to leap over a small crack in the sidewalk with theatrical, Olympic-level preparation."],
  ["The Matrix Dodge", "Pretend to dodge an invisible flying object in slow motion while walking down a park path."],
  ["The Stiff Robot", "Walk into a café moving only with rigid, robotic 90-degree joints."],
  ["The Invisible Dog", "Walk down the street holding your hand as if leading an invisible, very tiny dog on a leash."],
  ["The Speed Walk", "Power-walk at maximum athletic speed for 30 seconds while pumping your arms aggressively."],
  ["The Shadow Tag", "Try to step on your partner’s shadow 5 times without them stepping on yours while walking outside."],
  ["The Puddle Jump", "Leap over a non-existent puddle on a completely dry sidewalk with maximum dramatic effort."],
  ["The Statue Freeze", "Freeze completely motionless for 30 seconds the moment your partner says “Freeze!” in public."],
  ["The Sidewalk Hopscotch", "Play an imaginary game of hopscotch down the pavement for 10 metres."],
  ["The Low-Rider Walk", "Walk through a clothing section while crouched in a deep squat the entire time."],
  ["The Escalator Salute", "Salute every person going in the opposite direction on an escalator."],
  ["The Runway Walk", "Turn any crosswalk into a Paris fashion-week runway, complete with a fierce pose at the end."],
  ["The Caution Tape", "Walk around a totally clear, open area as if navigating an intense obstacle course."],
  ["The Slow-Mo High Five", "Initiate a high five with your partner that takes 20 full seconds to execute in public."],
  ["The Wind Tunnel", "Pretend you are walking into hurricane-force winds on a completely calm, still day."],
  ["The Duck Waddle", "Waddle like a duck for 5 steps every time you cross through an automatic door."],
  ["The Victory Lap", "Run around a park fountain or bench raising your arms like you just won Olympic gold."],
  ["The Giant Step", "Take absurdly massive, exaggerated giant steps down an entire block."],
  ["The Mirror Image", "Copy your partner’s exact physical posture and facial expression every time you stop walking."],
  ["The Trolley Pilot", "Announce “Preparing for takeoff!” every time you push the shopping cart into a new aisle."],
  ["The Cereal Debate", "Hold a serious, low-tone conversation with a box of cereal asking it why it costs so much."],
  ["The Guard Duty", "Stand guard outside the bathroom or an aisle with your arms crossed like an elite bouncer."],
  ["The Produce Whisperer", "Gently pat a watermelon, lean in close, and whisper “You’re doing great, buddy.”"],
  ["The Fashion Critique", "Hold up a ridiculously bright or ugly shirt and say out loud “This screams Met Gala.”"],
  ["The Frozen Food Chill", "Pretend to freeze solid for 5 seconds every time you open a freezer door in the supermarket."],
  ["The Price Tag Shock", "Gasp dramatically at the price of a regular loaf of bread as if it costs $10,000."],
  ["The Item Salute", "Salute every decorative pillow or candle you pass in a home-goods store."],
  ["The Grocery Bowler", "Gently roll a melon or coconut 2 feet down the aisle like a bowling ball — and catch it safely."],
  ["The Secret Stash", "Hide a totally normal box of pasta behind another box while looking around suspiciously."],
  ["The Basket Weightlifter", "Grunt loudly like a powerlifter every time you lift a light hand-basket."],
  ["The Mannequin Pose", "Stand next to a mannequin and adopt its exact pose until someone notices."],
  ["The Scent Enthusiast", "Smell a candle or shampoo, close your eyes, and describe an absurd memory it brings up. “Ah, smells like 1994 in Nebraska.”"],
  ["The Shopping List Monologue", "Read your shopping list out loud as if it’s a list of magical spell ingredients."],
  ["The Shoe Test", "Put on a shoe in a store and do a dramatic 5-metre sprint to test its performance."],
  ["The Cart Parallel Park", "Spend 45 seconds carefully parallel-parking your shopping cart next to a display."],
  ["The Vegetable Inspection", "Hold an avocado up to the light like a jeweller inspecting a rare diamond."],
  ["The Price Guess", "Have your partner point to an item and try to guess its price down to the exact cent within 3 seconds."],
  ["The Unwanted Match", "Place a random item (like a shoe) into your partner’s basket when they aren’t looking and act surprised when they find it."],
  ["The Supermarket Quiz", "Ask your partner 3 fast-paced trivia questions while standing in the dairy aisle."],
  ["The Toy Test", "Press the Try Me button on a musical toy and dance at enthusiasm-level 10 to it."],
  ["The Cart Co-Pilot", "Sit inside or lean heavily on the shopping cart while your partner pushes you down one aisle."],
  ["The Rejection Speech", "Put an item back on the shelf while apologizing to it. “It’s not you, it’s my budget.”"],
  ["The Bread Squeeze", "Squeeze a loaf of bread, look at your partner, and nod with deep, professional approval."],
  ["The Checkout Cheer", "Quietly chant “Scan! Scan! Scan!” every time the cashier scans an item."],
  ["The Bird Conference", "Stand near some pigeons or birds and pretend to hold a high-level diplomatic meeting with them."],
  ["The Tree Hug", "Walk up to a prominent park tree, give it a loving hug, and say “Thank you for the oxygen!”"],
  ["The Grass Inspector", "Kneel down on a park lawn and inspect a single blade of grass with intense concentration."],
  ["The Cloud Critic", "Point at a cloud and give a harsh 30-second artistic review of its shape and shading."],
  ["The Playground Swing", "Go sit on a playground swing and yell “Wheee!” with exaggerated childish joy."],
  ["The Park Bench Portrait", "Sit on a park bench and hold a regal pose while your partner takes a presidential photo of you."],
  ["The Leaf Catch", "Attempt to catch a falling leaf with maximum athletic drama and diving effort."],
  ["The Dog Whisperer", "Wave enthusiastically at every dog walking past and ignore their owners completely."],
  ["The Flower Serenade", "Sing a sweet 5-second lullaby to a flower bed in a public park."],
  ["The Bridge Guard", "Stand at the end of a small park bridge and demand a riddle or pun from your partner before letting them cross."],
  ["The Sun Greeting", "Stand facing the sun, raise both hands high, and yell “Greetings, sun orb!”"],
  ["The Rock Naming", "Pick up a smooth rock, name it Sir Bartholomew, and carry it proudly for the next 10 minutes."],
  ["The Fitness Instructor", "Do 5 intense star-jumps on a park path and shout “You’ve got this, team!” to passersby."],
  ["The Statue Stare-Down", "Hold a 30-second staring contest with a park statue or bust."],
  ["The Trail Guide", "Walk down a standard park dirt path while pointing out mundane things like “a very brown stick” or “a standard pebble.”"],
  ["The Puddle Splash", "Step into a small puddle with exaggerated splash-zone caution."],
  ["The Outdoor Opera", "Sing your partner’s name across an open park field in full opera vibrato."],
  ["The Duck Salute", "Stand at attention and salute a duck in a pond until it swims away."],
  ["The Sunset Review", "Give a live sports-style commentary on the sun going down or clouds moving."],
  ["The Pinecone Toss", "Try to gently toss a pinecone into a trash bin from 10 feet away like a professional basketball player."],
  ["The Bench Switch", "Every time you see an empty bench on a walk, sit on it for 3 seconds before moving on."],
  ["The Eco-Hero", "Pick up a single piece of litter, hold it high like the Stanley Cup, and deposit it in the bin."],
  ["The Bark Texture Test", "Touch the bark of three different trees and rank them from softest to roughest out loud."],
  ["The Shadow Puppet", "Use a streetlamp to make a shadow puppet on a wall at night."],
  ["The Weather Forecast", "Stand in the middle of a square and give a live weather update using your hand as a microphone."],
  ["The Pinky Lift", "Drink every beverage for the rest of the meal with your pinky finger extended as far as possible."],
  ["The Food Critic", "Take one bite of your food, close your eyes, chew for 15 seconds, and give a complex, pretentious review."],
  ["The Secret Toast", "Stand up at a restaurant table, raise your water glass, and toast to “The triumph of the potato!”"],
  ["The Fork Swap", "Ask your partner to trade forks with you halfway through a meal for luck."],
  ["The Napkin Origami", "Attempt to fold your paper napkin into a swan (or a blob) and present it as a gift to the server."],
  ["The Chef Compliment", "Ask the server to send your personal compliments to the chef specifically for the tap water."],
  ["The Salt Inspection", "Inspect a single grain of salt on your table with extreme focus before eating it."],
  ["The Fancy Sip", "Swirl your water glass, smell it, and declare “Ah, crisp tap notes with a hint of pipe rust.”"],
  ["The Table Drummer", "Play a 5-second drum solo on the edge of the dining table using chopsticks or straws."],
  ["The Bread Basket Defense", "Guard the complimentary bread basket like a dragon guarding a pile of gold."],
  ["The Blindfolded Bite", "Close your eyes and let your partner feed you one mystery item off their plate."],
  ["The Menu Shield", "Read the entire menu while holding it fully open, covering your entire face."],
  ["The Slow Chew", "Chew a single french fry or bite of food 40 times while maintaining eye contact."],
  ["The Condiment Collector", "Ask for 3 different types of hot sauce or mustard and line them up like a potion lab."],
  ["The Ice Cube Catch", "Try to catch an ice cube from your glass using only your lips or tongue."],
  ["The Dramatic Drop", "If a napkin falls on the floor, gasp dramatically as if a precious artifact was lost."],
  ["The Pepper Grinder", "Tell the server “when” to stop grinding pepper only after an uncomfortably long time."],
  ["The Straw Whistle", "Try to blow through your drink straw to make a whistling or bubble noise for 5 seconds."],
  ["The Sugar Packet Tower", "Build a 3-story tower using sugar packets at the table without it falling over."],
  ["The Reverse Order", "Read your dessert order backward to your partner first before telling the server."],
  ["The Royal Dab", "Dab the corners of your mouth with a napkin using extreme, delicate, aristocratic movements."],
  ["The Toothpick Art", "Create a mini sculpture using 4 toothpicks on the table."],
  ["The Food Swap Offer", "Offer a total stranger at the next table one of your fries in exchange for one of theirs."],
  ["The Plate Rotation", "Rotate your dinner plate 90 degrees after every 3 bites."],
  ["The Final Bite Ceremony", "Hold a moment of silence for the final bite of your meal before eating it."],
  ["The DJ Intro", "Introduce every song that comes on the radio like an over-caffeinated morning drive-time DJ."],
  ["The Traffic Light Cheer", "Cheer loudly with joy every time a red traffic light turns green."],
  ["The GPS Voice", "Speak only in a monotone, robotic turn-by-turn GPS navigation voice for 10 minutes."],
  ["The Toll Booth Wave", "Give a royal two-handed wave to the toll camera or automatic gate sensor."],
  ["The Seatbelt Click", "Say “Buckle up for safety!” in a 1950s public-safety announcement voice every time you enter a car."],
  ["The Drive-Thru Opera", "Sing your drive-thru order into the speaker box."],
  ["The Car Park Spotter", "Point out open parking spots like an excited commentator reporting a sports play."],
  ["The Dashboard Drummer", "Perform a high-energy dashboard drum session during an entire red light."],
  ["The Window Wave", "Wave at passengers in the car next to you at a red light until someone waves back."],
  ["The Parallel Park Cheer", "Give your partner a standing ovation after they successfully park the car."],
  ["The Mirror Check", "Check your rearview mirror, fix your hair dramatically, and whisper “Looking sharp, kid.”"],
  ["The Wiper Sync", "Try to wipe your hands back and forth in perfect synchronization with the windshield wipers."],
  ["The Tunnel Horn", "Honk the horn or say “BEEP BEEP” in a high-pitched voice every time you drive through a tunnel."],
  ["The Scenic Tour Guide", "Point out a completely normal gas station or building like it’s a world-famous landmark."],
  ["The Speed Bump Drama", "Ooh and aah loudly every time the car goes over a small speed bump."],
  ["The Air Guitar Solo", "Perform an intense air guitar solo in the passenger seat during a song."],
  ["The Indicator Beatbox", "Beatbox in perfect time with the click of the car’s turn signal."],
  ["The Gas Pump Countdown", "Stand at the gas pump and count down the dollars out loud like a rocket launch."],
  ["The Glovebox Search", "Open the glovebox, look inside mysteriously, and say “The documents are safe.”"],
  ["The Seat Adjustment", "Adjust your car seat back and forth 3 times while making mechanical hydraulic sounds."],
  ["The Headrest Hug", "Turn around and hug your seat headrest for 5 seconds while parked."],
  ["The Car Wash Reaction", "Act terrified of the car-wash brushes while sitting inside the vehicle."],
  ["The Backseat Driver", "Sit in the backseat and give instructions using a fake British accent."],
  ["The Cup Holder Praise", "Compliment the car’s cup holders for their sturdy design and reliability."],
  ["The Parking Ticket Relief", "Check a parking-space line, nod approvingly, and say “Flawless alignment.”"],
  ["The MasterChef Critique", "Critique your own glass of tap water as if Gordon Ramsay is judging your performance."],
  ["The Cooking Show Host", "Present the process of making simple toast or cereal to an imaginary TV audience."],
  ["The Fridge Inspector", "Open the fridge, stare inside for 10 seconds, close it, and whisper “Not today, old friend.”"],
  ["The Microwave Countdown", "Karate-chop the air right as the microwave timer hits 0:00."],
  ["The Spice Rack Tasting", "Smell 3 random spices from the pantry and name the imaginary dish they belong in."],
  ["The Spoon Balance", "Balance a plastic or metal spoon on your nose for 10 full seconds."],
  ["The Oven Mitt Hands", "Keep thick oven mitts on your hands for 10 minutes while trying to do daily tasks."],
  ["The Dramatic Pour", "Pour a glass of juice or milk from high above the cup like a fancy tea master."],
  ["The Kettle Sing-Along", "Whistle or hum in harmony with the kettle as it boils water."],
  ["The Pantry Inventory", "Read out the expiration dates of 5 canned goods like a military roll call."],
  ["The Dishwashing DJ", "Beatbox using the sounds of dishes clinking and water running in the sink."],
  ["The Ice Cube Drop", "Drop an ice cube down your own shirt and hold a straight face for 5 seconds."],
  ["The Cutting Board Chop", "Chop a vegetable with exaggerated ninja-style sound effects. HI-YA!"],
  ["The Apron Runway", "Put on an apron and strut across the kitchen like a high-fashion model."],
  ["The Toaster Jump", "Jump in the air at the exact moment the toaster pops up your bread."],
  ["The Trash Can Shot", "Attempt a 3-point basketball shot into the kitchen bin using a crumpled paper towel."],
  ["The Snack Guard", "Guard the pantry door and demand a password before letting your partner grab a snack."],
  ["The Blender Reaction", "Stand back and cover your ears in dramatic shock whenever the blender turns on."],
  ["The Fruit Bowl Pose", "Arrange 3 pieces of fruit into a face on the kitchen counter."],
  ["The Dish Towel Cape", "Tie a kitchen tea-towel around your neck like a superhero cape while wiping counters."],
  ["The Timer Alarm Dance", "Do a high-energy dance for the entire duration of a kitchen timer ringing."],
  ["The Recipe Accent", "Read a recipe out loud using a heavy, dramatic French chef accent."],
  ["The Spoon Mic", "Use a wooden spoon as a microphone and belt out a 10-second pop anthem."],
  ["The Mug Selection", "Spend 60 seconds deeply analyzing which coffee mug best matches your soul today."],
  ["The Sink Salute", "Salute the kitchen sink after washing every single dish."],
  ["The Movie Trailer Voice", "Read the Netflix movie descriptions out loud in a deep, dramatic movie-trailer voice."],
  ["The Remote Presenter", "Present the TV remote to your partner on a decorative pillow like a royal crown."],
  ["The Commercial Break Sprint", "Try to run to the kitchen, grab a glass of water, and get back before a 30-second ad ends."],
  ["The Gasps of Shock", "Gasp dramatically at every single plot twist or minor character entrance during a show."],
  ["The Cushion Fort", "Build a mini cushion tower on the sofa and sit inside or behind it for 15 minutes."],
  ["The Subtitle Reader", "Read all the subtitles out loud in an exaggerated robotic voice."],
  ["The Sofa Slow-Mo", "Collapse onto the couch in cinematic slow motion after coming back from another room."],
  ["The Remote Battery Trick", "Slap the back of the TV remote, shake it, and say “Work, you ancient magic!”"],
  ["The Popcorn Catch", "Try to catch a piece of thrown popcorn in your mouth 3 times in a row."],
  ["The Character Dub", "Mute the TV for 30 seconds and invent funny dialogue for the characters on screen."],
  ["The Blanket Burrito", "Roll yourself up completely in a blanket like a burrito and stay that way for 10 minutes."],
  ["The Standing Ovation", "Give a standing ovation at the end of a single episode of a TV show."],
  ["The Pause Button Freeze", "Freeze your body in whatever awkward position you were in every time the TV is paused."],
  ["The Snack Tax", "Demand a 1-bite snack tax every time your partner brings food to the couch."],
  ["The TV Critic", "Give a 30-second analytical review of a commercial right after it finishes airing."],
  ["The Sofa Synchronized Swim", "Lie on the couch and move your legs like a synchronized swimmer for 10 seconds."],
  ["The Pillow Shield", "Use a couch pillow as a shield every time an intense or scary scene appears on screen."],
  ["The Volume Preference", "Adjust the TV volume so it must end on an even number or a multiple of 5."],
  ["The Couch Mountain", "Clamber over the top of the couch instead of walking around it to sit down."],
  ["The Actor Impression", "Attempt to copy the exact expression of the main actor on screen right now."],
  ["The Intro Theme Dance", "Create a custom 10-second dance routine for the show’s intro song."],
  ["The Remote Hold", "Hold the TV remote high in the air like Excalibur before pressing play."],
  ["The Snack Tower", "Stack 4 crackers or chips on your forehead while lying flat on the couch."],
  ["The Dramatic Pause", "Pause mid-sentence while talking on the couch and stare into space for 5 seconds."],
  ["The Blanket Share", "Offer 90% of the blanket to your partner and keep only 10% for yourself, dramatically."],
  ["The Bed Jump", "Dive onto the bed like a swimmer diving into an Olympic pool."],
  ["The Pillow Fight Challenge", "Challenge your partner to a pillow fight using only soft, gentle taps."],
  ["The Slippers Shuffle", "Walk around the bedroom wearing slippers on the wrong feet for 10 minutes."],
  ["The Bed Folding Sheet", "Try to fold a fitted sheet perfectly while narrating your frustration."],
  ["The Sock Puppets", "Put socks on your hands and hold a 30-second deep philosophical conversation between them."],
  ["The Pyjama Fashion Show", "Put on your pajamas in a funny combination and model them down the hallway."],
  ["The Nightstand Cleanup", "Re-organise 3 items on your nightstand with surgical precision."],
  ["The Sleeping Beauty", "Pretend to be fast asleep and snoring loudly 2 seconds after hitting the pillow."],
  ["The Alarm Clock Stare", "Hold an intense staring contest with the bedroom clock for 30 seconds."],
  ["The Duvet Wave", "Shake out the duvet so high it creates a huge wind gust across the bed."],
  ["The Bedside Monologue", "Stand next to the bed and recite a dramatic bedtime poem to your partner."],
  ["The Blindfolded Sock Match", "Try to pair up 3 sets of socks from a laundry basket while blindfolded."],
  ["The Monster Inspection", "Check under the bed for monsters using a phone flashlight and report back."],
  ["The Pillow Fluff", "Fluff a pillow with extreme violence, then gently pat it down nicely."],
  ["The Closet Entrance", "Walk out of the closet like a magician stepping out of a magic box."],
  ["The Yawn Infection", "Fake a giant, exaggerated yawn and see how long it takes your partner to yawn back."],
  ["The Eye Mask", "Wear an eye mask on your chin like a beard for 15 minutes while hanging out in the bedroom."],
  ["The Mattress Bounce", "Sit on the edge of the bed and bounce 5 times while yelling “Springy!”"],
  ["The Sock Roll Toss", "Try to throw a rolled-up pair of socks into the laundry hamper from across the room."],
  ["The Curtains Dramatics", "Pull open the bedroom curtains dramatically every morning while shouting “Good day, world!”"],
  ["The PJ Tuck", "Tuck your pajama shirt completely into your pajama trousers in a high-waisted fashion."],
  ["The Blanket Tug", "Play a 10-second game of tug-of-war using a blanket corner."],
  ["The Bedhead Selfie", "Take a high-fashion model selfie with your worst morning bedhead hair."],
  ["The Pillow Throne", "Stack every pillow in the room into a giant throne and sit on top of it."],
  ["The Under-Bed Retrieval", "Slide on your stomach under the bed to retrieve an imaginary lost coin."],
  ["The Toothbrush Solo", "Sing a song through a mouthful of toothpaste foam while brushing your teeth."],
  ["The Mirror Pep Talk", "Give yourself an intense, motivational locker-room speech in the bathroom mirror."],
  ["The Soap Opera Gasp", "Look at your reflection, gasp in horror, and whisper “It was you all along!”"],
  ["The Shampoo Mohawk", "Style your wet hair into a giant shampoo mohawk and present it to your partner."],
  ["The Towel Turban", "Walk around the house wearing a bath towel wrapped up like a royal turban."],
  ["The Soap Bubbles", "Blow a soap bubble off your hand and try to keep it in the air for 5 seconds."],
  ["The Mirror Wink", "Give your reflection a smooth wink every time you wash your hands today."],
  ["The Toilet Roll Rollout", "Origami-fold the end of the toilet paper roll into a neat hotel triangle."],
  ["The Cold Water Challenge", "Splash cold water on your face like a movie protagonist recovering from a dramatic night."],
  ["The Foggy Mirror Art", "Draw a funny stick figure or heart in the steam on the bathroom mirror."],
  ["The Hairbrush Singer", "Use a hairbrush as a microphone and perform a dramatic rock-ballad solo."],
  ["The Scale Weigh-In", "Step onto the bathroom scale and react like a professional boxer at a weigh-in."],
  ["The Duck Voice", "Speak in a Donald Duck voice while rinsing your mouth out with mouthwash."],
  ["The Towel Cape", "Wear a bath towel as a superhero cape while brushing your hair."],
  ["The Hand Soap Review", "Give a detailed 30-second review of the scent and foam quality of the hand soap."],
  ["The Bathmat Balance", "Stand on one leg on the bathroom mat for 30 seconds while drying off."],
  ["The Tap Water Connoisseur", "Taste the bathroom tap water and compare it to the kitchen tap water out loud."],
  ["The Lotion Art", "Squirt hand lotion onto your palm in the shape of a happy smiley face."],
  ["The Shower Opera", "Sing a single operatic note as loud as you can to test the bathroom acoustics."],
  ["The Mirror High-Five", "Give your own reflection a gentle high-five on the glass."],
  ["The Toothpaste Precision", "Apply a perfectly symmetrical blob of toothpaste to your brush on the first try."],
  ["The Hair Flip", "Perform a dramatic hair flip every time you leave the bathroom today."],
  ["The Bathroom Entrance", "Knock on the bathroom door 3 times and say “Housekeeping!” before entering."],
  ["The Floss Master", "Floss your teeth with intense speed and rhythm like playing a string instrument."],
  ["The Curtain Peek", "Peek out from behind the shower curtain like a sneaky cartoon spy."],
  ["The Vacuum Guitar", "Use the vacuum-cleaner pipe as an electric guitar during a song cleaning session."],
  ["The Dustpan Curling", "Sweep dust into a pile and use the broom like a curling broom on an ice rink."],
  ["The Laundry Basket Basket", "Try to throw folded laundry items into the basket from 5 feet away."],
  ["The Spray Bottle Duel", "Hold a cleaner spray bottle like a cowboy holding a revolver in a Western."],
  ["The Sock Matching Race", "Race your partner to see who can match 5 pairs of clean socks faster."],
  ["The Ironing Precision", "Iron a single shirt while talking like a strict military drill sergeant."],
  ["The Bin Bag Whip", "Whip open a fresh trash bag with maximum dramatic snapping noise."],
  ["The Floor Mop Dance", "Dance a slow waltz with the mop while cleaning the hardwood floor."],
  ["The Window Wipe Squeak", "Wipe a glass window until it makes 3 distinct loud squeaky sounds."],
  ["The Clutter Inspector", "Point at a small pile of clutter and shout “Containment breach in sector 4!”"],
  ["The Dishwasher Loader", "Load the dishwasher like a master Tetris champion fitting blocks together."],
  ["The Feather Duster Ninja", "Dust a bookshelf using fast, martial-arts style feather-duster flicks."],
  ["The Sock Slide", "Wear clean socks and slide across the polished kitchen floor like a rockstar."],
  ["The Recycling Crusher", "Crush a plastic bottle or can using your foot with a dramatic superhero stomp."],
  ["The Sponge Squeeze", "Squeeze a wet sponge completely dry using only one hand and maximum muscle effort."],
  ["The Laundry Mountain", "Pose atop a pile of clean unfolded laundry like a king on a mountain peak."],
  ["The Table Wipe Polish", "Polish a dining table surface until you can see your reflection clearly."],
  ["The Broom Balance", "Balance a broom vertically on the palm of your hand for 5 seconds."],
  ["The Trash Run Sprint", "Sprint to take the household trash out to the external bins in record time."],
  ["The Sock Sort Sortie", "Sort clean laundry while speaking only in radio command jargon. “Roger, blue sock secured.”"],
  ["The Mirror Wipe Reflection", "Wipe a mirror and make a different funny face after every single wipe."],
  ["The Robot Vacuum Escort", "Walk behind the robot vacuum acting like its personal royal bodyguard."],
  ["The Cushion Fluff Stomp", "Punch or fluff a couch cushion 3 times while yelling “HYAH!”"],
  ["The Organised Drawer", "Tidy up one messy drawer completely and present it to your partner like a museum piece."],
  ["The Chore Medal", "Award yourself a fake gold medal after finishing a minor cleaning task."],
  ["The Doorframe High-Five", "Jump up and high-five the top of a doorframe every time you pass through it today."],
  ["The Hallway Strut", "Turn any hallway walk into a fierce, dramatic fashion-runway strut."],
  ["The Light Switch Rave", "Flick the light switch on and off twice quickly while saying “UNCE UNCE UNCE.”"],
  ["The Pet Interview", "Hold an imaginary microphone up to a household pet and ask them about their daily schedule."],
  ["The Echo Test", "Shout “ECHO!” into an empty hallway or room and wait silently for 3 seconds."],
  ["The Floor Is Lava", "Yell “The floor is lava!” and get both feet off the ground within 3 seconds."],
  ["The Plant Conversation", "Have a 15-second encouraging chat with a houseplant about its growth progress."],
  ["The Staircase Announcement", "Announce your arrival out loud every time you walk down the stairs."],
  ["The Footstep Sync", "Try to match your partner’s footstep cadence perfectly as you walk around the house."],
  ["The Door Knock Rhythm", "Knock on a door using a famous song rhythm — Shave and a Haircut works."],
  ["The Thermostat Guard", "Stand in front of the thermostat with your arms crossed like a museum guard."],
  ["The Ceiling Fan Wave", "Wave at the ceiling fan every time you turn it on or off."],
  ["The Carpet Footprint", "Walk on your tiptoes across a plush carpet to leave invisible footprints."],
  ["The Doorknob Polish", "Wipe a doorknob with your sleeve and whisper “Prismatic brilliance!”"],
  ["The Window Wave Home", "Wave through the window at your partner when they step out into the yard or drive."],
  ["The Wall Sit Hold", "Hold a wall sit for 30 seconds while casually humming a tune."],
  ["The Corner Peek", "Peek around every doorway corner like a sneaky spy before entering a new room."],
  ["The High-Five Trap", "Offer your partner a high-five, pull it away at the last second, and smooth back your hair."],
  ["The Blind Walk", "Close your eyes and let your partner guide you through two rooms using only verbal cues."],
  ["The Statue Freeze Home", "Freeze completely motionless whenever you hear a specific word chosen by your partner today."],
  ["The Slow-Mo Hug", "Give your partner a hug that takes 15 seconds to slowly execute."],
  ["The Reverse Walk", "Walk backward from the living room to the kitchen to fetch a glass of water."],
  ["The Whisper Gossip", "Lean in and whisper a completely mundane fact (“The sky is blue today”) like it’s a huge secret."],
  ["The Shadow Chase", "Try to catch your partner’s hand shadow on the wall using your own hand shadow."],
  ["The Final Bow", "Take a deep, theatrical bow to your partner before leaving any room."],
];

export const CHICKEN_DARES: ChickenDare[] = RAW.map(([name, body], index) => {
  const n = index + 1;
  const pack = packFor(n);
  return {
    id: `c${String(n).padStart(3, "0")}`,
    n,
    yard: yardFor(pack),
    pack,
    name,
    body,
  };
});
