export type DateTimeTag = "day" | "night" | "anytime";
export type DateCostTag = "free" | "low" | "splurge";
export type DateVibeTag =
  | "cozy"
  | "active"
  | "spicy"
  | "creative"
  | "social"
  | "relaxed";
export type DateLocationTag = "home" | "out";

export type DateIdea = {
  id: string;
  title: string;
  blurb: string;
  time: DateTimeTag;
  cost: DateCostTag;
  vibe: DateVibeTag;
  location: DateLocationTag;
};

export type DateIdeaFilters = {
  location: DateLocationTag | "all";
  time: DateTimeTag | "all";
  cost: DateCostTag | "all";
  vibe: DateVibeTag | "all";
};

export const DEFAULT_DATE_FILTERS: DateIdeaFilters = {
  location: "all",
  time: "all",
  cost: "all",
  vibe: "all",
};

export const DATE_LOCATION_FILTERS = [
  { id: "all" as const, label: "All" },
  { id: "home" as const, label: "At-Home" },
  { id: "out" as const, label: "Out & About" },
];

export const DATE_TIME_FILTERS = [
  { id: "all" as const, label: "Anytime" },
  { id: "day" as const, label: "Daytime" },
  { id: "night" as const, label: "Nighttime" },
];

export const DATE_COST_FILTERS = [
  { id: "all" as const, label: "Any budget" },
  { id: "free" as const, label: "Free" },
  { id: "low" as const, label: "Under $30" },
  { id: "splurge" as const, label: "Splurge" },
];

export const DATE_VIBE_FILTERS = [
  { id: "all" as const, label: "Any vibe" },
  { id: "cozy" as const, label: "Cozy" },
  { id: "active" as const, label: "Active" },
  { id: "creative" as const, label: "Creative" },
  { id: "spicy" as const, label: "Spicy / Romantic" },
  { id: "relaxed" as const, label: "Relaxed" },
  { id: "social" as const, label: "Social" },
];

export const DATE_IDEAS: DateIdea[] = [
  {
    id: "the-living-room-fort",
    title: "The Living Room Fort",
    blurb: "Build an elaborate blanket fort with fairy lights, pillows, and watch a movie from childhood.",
    time: "anytime",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "blindfold-taste-test",
    title: "Blindfold Taste Test",
    blurb: "Blindfold each other and guess 5 secret pantry foods or sauces.",
    time: "night",
    cost: "low",
    vibe: "spicy",
    location: "home",
  },
  {
    id: "vinyl-wine",
    title: "Vinyl & Wine",
    blurb: "Put on a full album from start to finish with no phones, drinking your favorite wine/tea.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "diy-pizza-championship",
    title: "DIY Pizza Championship",
    blurb: "Buy pre-made dough and set up competing topping stations to judge the best slice.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "coupons-night",
    title: "Coupons Night",
    blurb: "Pick 3 digital app coupons from your collection and redeem them back-to-back.",
    time: "night",
    cost: "free",
    vibe: "spicy",
    location: "home",
  },
  {
    id: "powerpoint-night",
    title: "PowerPoint Night",
    blurb: "Create ridiculous 5-slide presentations explaining a niche passion, drama, or conspiracy theory.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "home",
  },
  {
    id: "the-two-player-video-game",
    title: "The Two-Player Video Game",
    blurb: "Beat a co-op game together in one sitting (e.g., It Takes Two or Overcooked).",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "home",
  },
  {
    id: "backyard-stargazing",
    title: "Backyard Stargazing",
    blurb: "Lay a heavy blanket on the lawn, download a constellation app, and star-track with warm drinks.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "spa-night",
    title: "Spa Night",
    blurb: "Charcoal face masks, foot soaks, warm towels, and full-body cucumber-water pampering.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "board-game-tournament",
    title: "Board Game Tournament",
    blurb: "Play 3 different fast-paced board or card games; winner gets a favor coupon.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "home",
  },
  {
    id: "fondue-night",
    title: "Fondue Night",
    blurb: "Melt cheese or chocolate and dip every fruit, pretzel, or meat left in the fridge.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "the-how-well-do-you-know-me-dinner",
    title: "The How Well Do You Know Me Dinner",
    blurb: "Cook a 3-course meal where each course is based on a milestone in your relationship.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "paint-sip-at-home",
    title: "Paint & Sip at Home",
    blurb: "Follow a watercolor or canvas tutorial on YouTube while sharing a bottle of wine.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "silent-disco",
    title: "Silent Disco",
    blurb: "Put on your headphones, sync a playlist, and dance around the dark living room together.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "home",
  },
  {
    id: "midnight-baking",
    title: "Midnight Baking",
    blurb: "Bake cookies or brownies from scratch past 11 PM and eat them warm out of the oven.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "youtube-retro-binge",
    title: "YouTube Retro Binge",
    blurb: "Watch old commercials, viral videos, and music videos from the year you both turned 12.",
    time: "night",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "massage-ambient-sounds",
    title: "Massage & Ambient Sounds",
    blurb: "Dim the lights, play rain sounds, and give each other 20-minute back massages.",
    time: "night",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "lego-building-night",
    title: "Lego Building Night",
    blurb: "Buy a medium Lego set and build it together while drinking hot cocoa.",
    time: "night",
    cost: "splurge",
    vibe: "creative",
    location: "home",
  },
  {
    id: "slow-dance-in-the-kitchen",
    title: "Slow Dance in the Kitchen",
    blurb: "Turn off the main lights, turn up a jazz playlist, and slow dance in the dark.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "tasting-flight-at-home",
    title: "Tasting Flight at Home",
    blurb: "Create your own tasting flight with 4 craft beers, chocolates, or cheeses.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "the-photo-album-deep-dive",
    title: "The Photo Album Deep Dive",
    blurb: "Scroll all the way back to the oldest photos on your phones and share the untold stories.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "indoor-picnic",
    title: "Indoor Picnic",
    blurb: "Lay a plaid blanket on the carpet, eat charcuterie, and listen to acoustic music.",
    time: "anytime",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "poetry-whiskey",
    title: "Poetry & Whiskey",
    blurb: "Read funny or deep poetry out loud while sipping a smooth drink.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "the-murder-mystery-game",
    title: "The Murder Mystery Game",
    blurb: "Buy a downloadable one-night murder mystery case and solve it together.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "learn-a-dance-routine",
    title: "Learn a Dance Routine",
    blurb: "Follow a 20-minute Salsa or Swing tutorial on YouTube in the living room.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "home",
  },
  {
    id: "diy-ice-cream-sundaes",
    title: "DIY Ice Cream Sundaes",
    blurb: "Buy 3 ice cream flavors and every outrageous topping you can find.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "dream-vacation-planning",
    title: "Dream Vacation Planning",
    blurb: "Plan a 100% hypothetical luxury $50,000 vacation down to the hotels and activities.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "home",
  },
  {
    id: "relationship-time-capsule",
    title: "Relationship Time Capsule",
    blurb: "Write letters to your future selves, lock them in a box, and pick an unlock date.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "audiobook-cuddle",
    title: "Audiobook Cuddle",
    blurb: "Lie in bed with the lights off and listen to 2 chapters of an engaging audiobook or thriller.",
    time: "night",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "diy-cocktail-mocktail-competition",
    title: "DIY Cocktail Mocktail Competition",
    blurb: "Mix drinks using only random pantry ingredients; rate each other's creations.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "sunset-tea-on-the-porch",
    title: "Sunset Tea on the Porch",
    blurb: "Sit outside during golden hour with a hot drink and zero digital devices.",
    time: "day",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "strip-poker-cards",
    title: "Strip Poker Cards",
    blurb: "Play a classic card game where every lost round costs an item of clothing.",
    time: "night",
    cost: "free",
    vibe: "spicy",
    location: "home",
  },
  {
    id: "read-out-loud",
    title: "Read Out Loud",
    blurb: "Pick a fiction book and take turns reading chapters out loud while the other rests their head in your lap.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "puzzle-podcast",
    title: "Puzzle & Podcast",
    blurb: "Put together a 500-piece puzzle while listening to a gripping true-crime or comedy podcast.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "the-nostalgia-dinner",
    title: "The Nostalgia Dinner",
    blurb: "Recreate the exact junk food or dinner you both loved eating as kids.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "sensory-massage",
    title: "Sensory Massage",
    blurb: "Take turns massaging each other using only feathers, warm towels, or ice cubes.",
    time: "night",
    cost: "free",
    vibe: "spicy",
    location: "home",
  },
  {
    id: "karaoke-at-home",
    title: "Karaoke at Home",
    blurb: "Use YouTube karaoke tracks and hairbrushes to sing 80s ballads at the top of your lungs.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "home",
  },
  {
    id: "binge-an-anime-foreign-mini-series",
    title: "Binge an Anime Foreign Mini-Series",
    blurb: "Watch a full 6-episode mini-series in a single night with subtitles.",
    time: "night",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "the-tarot-astrology-reading",
    title: "The Tarot Astrology Reading",
    blurb: "Look up each other's birth charts or pull tarot cards for fun interpretations.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "home",
  },
  {
    id: "make-homemade-pasta",
    title: "Make Homemade Pasta",
    blurb: "Flour the counter and roll out fresh pasta dough from scratch.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "pancake-art-challenge",
    title: "Pancake Art Challenge",
    blurb: "Use squeeze bottles to make shaped pancakes (animals, hearts, faces) for dinner.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "hot-tub-bath-pampering",
    title: "Hot Tub Bath Pampering",
    blurb: "Fill the tub with bubbles, bath salts, and float LED candles on the water.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "indoor-camping",
    title: "Indoor Camping",
    blurb: "Sleep in a tent or sleeping bags on the living room rug with a fake fireplace on the TV.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "language-crash-course",
    title: "Language Crash Course",
    blurb: "Spend 45 minutes learning basic phrases of a language you both want to learn.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "home",
  },
  {
    id: "origami-tea",
    title: "Origami & Tea",
    blurb: "Fold paper figures while listening to calming ambient music.",
    time: "night",
    cost: "free",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "sketch-each-other",
    title: "Sketch Each Other",
    blurb: "Spend 10 minutes drawing a portrait of each other without looking down at the paper.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "home",
  },
  {
    id: "the-taco-stand-off",
    title: "The Taco Stand Off",
    blurb: "Make 3 different styles of street tacos and vote on the winning recipe.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "home",
  },
  {
    id: "late-night-cereal-party",
    title: "Late-Night Cereal Party",
    blurb: "Buy 4 sugary kids cereals you never usually buy and eat them while watching cartoons.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "diy-body-scrub",
    title: "DIY Body Scrub",
    blurb: "Mix sugar, coconut oil, and essential oils to use in a warm bath or shower together.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "home",
  },
  {
    id: "gratitude-memory-night",
    title: "Gratitude & Memory Night",
    blurb: "Go through The Jar in the app and read past appreciations out loud.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "home",
  },
  {
    id: "golden-hour-hike",
    title: "Golden Hour Hike",
    blurb: "Find a local trail and time your hike to reach the lookout right at sunset.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "sunrise-breakfast",
    title: "Sunrise Breakfast",
    blurb: "Wake up before dawn, drive to a scenic spot with thermos coffee, and watch the sunrise.",
    time: "day",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "botanical-gardens-walk",
    title: "Botanical Gardens Walk",
    blurb: "Stroll through a greenhouse or outdoor flora garden taking macro photos.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "kayak-canoe-rental",
    title: "Kayak Canoe Rental",
    blurb: "Rent a double kayak and paddle down a local river or lake.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "farmers-market-run",
    title: "Farmers Market Run",
    blurb: "Walk through a local Saturday market, sampling produce and buying fresh bread.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "beach-bonfire",
    title: "Beach Bonfire",
    blurb: "Build a small beach fire where legal, toast marshmallows, and listen to the waves.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "stargazing-in-the-country",
    title: "Stargazing in the Country",
    blurb: "Drive 30 minutes outside town away from light pollution to lie on the hood of the car.",
    time: "night",
    cost: "free",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "fruit-picking",
    title: "Fruit Picking",
    blurb: "Visit a local orchard to pick fresh strawberries, apples, or berries straight from the trees.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "disc-golf-run",
    title: "Disc Golf Run",
    blurb: "Buy two cheap frisbees and play a round at a local public disc golf course.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "park-bench-people-watching",
    title: "Park Bench People Watching",
    blurb: "Grab iced coffees, sit on a busy park bench, and invent backstories for passersby.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "outdoor-cinema",
    title: "Outdoor Cinema",
    blurb: "Find an open-air movie screening or drive-in theater for a retro movie night.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "bike-riding-exploration",
    title: "Bike Riding Exploration",
    blurb: "Rent or ride your bikes along a scenic rail trail or waterfront path.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "stand-up-paddleboarding",
    title: "Stand-Up Paddleboarding",
    blurb: "Balance on a board together on calm lake water.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "scenic-drive-with-no-destination",
    title: "Scenic Drive with No Destination",
    blurb: "Toss a coin at every intersection (Heads = Right, Tails = Left) for 30 minutes.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "river-floating",
    title: "River Floating",
    blurb: "Grab inflatable tubes and float down a gentle local river on a hot afternoon.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "picnic-in-the-park",
    title: "Picnic in the Park",
    blurb: "Pack a blanket, baguette, cheeses, and grapes for a sunny afternoon park lunch.",
    time: "day",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "feed-the-ducks-birds",
    title: "Feed the Ducks Birds",
    blurb: "Buy proper bird seed and visit a local pond or wetland.",
    time: "day",
    cost: "free",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "cliffside-lookout-picnic",
    title: "Cliffside Lookout Picnic",
    blurb: "Drive to the highest elevation near you and eat lunch overlooking the view.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "outdoor-yoga-session",
    title: "Outdoor Yoga Session",
    blurb: "Lay out mats at a quiet park or beach corner and follow a flow together.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "wildlife-sanctuary-visit",
    title: "Wildlife Sanctuary Visit",
    blurb: "Walk through a native wildlife park or sanctuary.",
    time: "day",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "catch-release-fishing",
    title: "Catch & Release Fishing",
    blurb: "Try your hand at quiet lake fishing off a wooden pier.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "full-moon-walk",
    title: "Full Moon Walk",
    blurb: "Take a night hike along an open, safe trail lit only by a bright full moon.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "corn-maze-pumpkin-patch",
    title: "Corn Maze Pumpkin Patch",
    blurb: "Get lost in a seasonal autumn maze or pick out home decor.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "rooftop-bar-drinks",
    title: "Rooftop Bar Drinks",
    blurb: "Find the highest accessible rooftop bar in town for a sunset cocktail.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "bouldering-outdoor-climbing",
    title: "Bouldering Outdoor Climbing",
    blurb: "Try low-height outdoor rock scrambling or guided climbing.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "flower-market-run",
    title: "Flower Market Run",
    blurb: "Walk through a wholesale flower market and build custom bouquets for each other.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "geocaching",
    title: "Geocaching",
    blurb: "Download a free geocaching app and hunt for hidden physical containers around your town.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "harbor-lake-ferry-ride",
    title: "Harbor Lake Ferry Ride",
    blurb: "Take a local commuter ferry just for the water view and breeze.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "lawn-bowls-bocce",
    title: "Lawn Bowls Bocce",
    blurb: "Play a low-key game of outdoor bocce or lawn bowls at a local club.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "cold-plunge-hot-towels",
    title: "Cold Plunge & Hot Towels",
    blurb: "Take a dip in a cold ocean/river followed immediately by warm blankets and hot drinks.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "outdoor-photography-tour",
    title: "Outdoor Photography Tour",
    blurb: "Pick a theme (e.g., red objects, reflections) and take photos around town.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "visit-an-organic-farm",
    title: "Visit an Organic Farm",
    blurb: "Tour a working local farm, pet animals, and buy fresh milk or honey.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "waterfall-walk",
    title: "Waterfall Walk",
    blurb: "Hike to a local waterfall and enjoy the spray and natural sounds.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "barefoot-beach-stroll",
    title: "Barefoot Beach Stroll",
    blurb: "Walk along the tide line holding hands and collecting unique shells.",
    time: "day",
    cost: "free",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "outdoor-hammocking",
    title: "Outdoor Hammocking",
    blurb: "String up a double hammock between two trees in a quiet park and read together.",
    time: "day",
    cost: "free",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "historical-walking-tour",
    title: "Historical Walking Tour",
    blurb: "Download a self-guided historical audio tour of your towns oldest precinct.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "night-market-stroll",
    title: "Night Market Stroll",
    blurb: "Wander through street stalls, under string lights, eating finger foods.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "outdoor-ice-skating",
    title: "Outdoor Ice Skating",
    blurb: "Lace up skates at a seasonal outdoor rink with hot cocoa in hand.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "kite-flying",
    title: "Kite Flying",
    blurb: "Buy a cheap stunt kite and head to an open windy hill or beach.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "caves-grotto-tour",
    title: "Caves Grotto Tour",
    blurb: "Explore local limestone caves or rocky coastal grottos.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "bridge-sunset-view",
    title: "Bridge Sunset View",
    blurb: "Walk to the middle of a pedestrian bridge right as the sun dips below the horizon.",
    time: "day",
    cost: "free",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "public-sculpture-park",
    title: "Public Sculpture Park",
    blurb: "Walk among outdoor art installations and debate their meanings.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "foraging-walk",
    title: "Foraging Walk",
    blurb: "Take an introductory guided mushroom or wild herb foraging walk.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "skateboard-rollerblade",
    title: "Skateboard Rollerblade",
    blurb: "Glide along a smooth paved coastal or park track together.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "outdoor-swimming-hole",
    title: "Outdoor Swimming Hole",
    blurb: "Skip the public pool and find a natural river bend or swimming hole.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "nighttime-city-skyline",
    title: "Nighttime City Skyline",
    blurb: "Drive to a hill overlooking the city lights and listen to music.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "scenic-train-ride",
    title: "Scenic Train Ride",
    blurb: "Buy a return ticket on a regional train line just for the views out the window.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "plant-nursery-stroll",
    title: "Plant Nursery Stroll",
    blurb: "Walk through massive greenhouses, picking out a small houseplant to take home.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "watch-storms-waves",
    title: "Watch Storms Waves",
    blurb: "Sit in a parked car near the ocean or overlooking a valley during heavy weather.",
    time: "anytime",
    cost: "free",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "campfire-marshmallow-toast",
    title: "Campfire Marshmallow Toast",
    blurb: "Set up a small backyard firepit and make traditional s'mores.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "progressive-dinner",
    title: "Progressive Dinner",
    blurb: "Eat appetizers at restaurant A, main course at restaurant B, and dessert at restaurant C.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "food-truck-crawl",
    title: "Food Truck Crawl",
    blurb: "Find a food truck park and split 1 dish from 3 different trucks.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "speakeasy-hunt",
    title: "Speakeasy Hunt",
    blurb: "Track down a hidden entrance bar or speakeasy in your city for a craft cocktail.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "diner-late-night-coffee",
    title: "Diner Late-Night Coffee",
    blurb: "Hit a 24-hour diner at midnight for milkshakes and greasy fries.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "blind-order-challenge",
    title: "Blind Order Challenge",
    blurb: "Go to a restaurant and let the waiter pick your meals entirely.",
    time: "night",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "hole-in-the-wall-exploration",
    title: "Hole-in-the-Wall Exploration",
    blurb: "Pick a cuisine youve never tried (e.g., Ethiopian, Nepalese) at a local small spot.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "brewery-hopping",
    title: "Brewery Hopping",
    blurb: "Sample paddles at two local craft breweries.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "bakery-crawl",
    title: "Bakery Crawl",
    blurb: "Visit 3 bakeries in one morning, buying 1 signature pastry at each to rank them.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "high-tea",
    title: "High Tea",
    blurb: "Dress up for a traditional afternoon tea with tier stands and scones.",
    time: "day",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "ramen-shop-night",
    title: "Ramen Shop Night",
    blurb: "Slurp hot bowls of authentic ramen in a small, steaming bar.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "supermarket-roulette",
    title: "Supermarket Roulette",
    blurb: "Walk into a grocery store; partner A picks the protein, partner B picks the secret sauce. Cook it.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "cheap-eats-feast",
    title: "Cheap Eats Feast",
    blurb: "Set a strict $20 total limit for both of you to get full on street food.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "cocktail-masterclass",
    title: "Cocktail Masterclass",
    blurb: "Attend a 1-hour mixology class to learn how to shake classic drinks.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "ice-cream-crawl",
    title: "Ice Cream Crawl",
    blurb: "Hit 3 gelato shops back-to-back, getting 1 single scoop at each.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "wine-cheese-tasting",
    title: "Wine & Cheese Tasting",
    blurb: "Visit a local vineyard or cheese shop for a guided pairing flight.",
    time: "day",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "breakfast-for-dinner",
    title: "Breakfast for Dinner",
    blurb: "Hit a late-night cafe or cook a full spread of pancakes and bacon at 8 PM.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "dine-in-blackout-darkness",
    title: "Dine in Blackout Darkness",
    blurb: "Book a table at a dark dining experience or eat blindfolded.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "dim-sum-brunch",
    title: "Dim Sum Brunch",
    blurb: "Order cart after cart of steamed dumplings and tea at a busy Dim Sum hall.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "dessert-only-night",
    title: "Dessert Only Night",
    blurb: "Skip dinner completely and go straight to a fancy dessert lounge for two courses of sweets.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "tapas-sharing",
    title: "Tapas Sharing",
    blurb: "Order 6 small sharing plates at a Spanish tapas bar with sangria.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "international-grocery-adventure",
    title: "International Grocery Adventure",
    blurb: "Visit an Asian or South American supermarket and buy 5 mystery snacks to taste.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "oyster-champagne-bar",
    title: "Oyster & Champagne Bar",
    blurb: "Treat yourselves to half a dozen fresh oysters and a glass of bubbles.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "pho-on-a-rainy-day",
    title: "Pho on a Rainy Day",
    blurb: "Warm up over massive, steaming bowls of traditional Vietnamese Pho.",
    time: "day",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "korean-bbq",
    title: "Korean BBQ",
    blurb: "Grill your own meats at the table surrounded by side dishes.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "izakaya-night",
    title: "Izakaya Night",
    blurb: "Sit at a busy wooden Japanese bar ordering yakitori skewers and draft beer.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "fondue-restaurant",
    title: "Fondue Restaurant",
    blurb: "Visit a dedicated fondue spot for bubbling Gruyere and melted chocolate.",
    time: "night",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "street-food-night-market",
    title: "Street Food Night Market",
    blurb: "Grab skewers, bao, and bubble tea while browsing stalls.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "donut-taste-test",
    title: "Donut Taste Test",
    blurb: "Buy 6 gourmet donuts from a specialty shop and rate them on a 1-10 scale.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "churros-hot-chocolate",
    title: "Churros & Hot Chocolate",
    blurb: "Sit at a late-night Spanish cafe dipping warm churros in melted fudge.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "whiskey-gin-bar",
    title: "Whiskey Gin Bar",
    blurb: "Order a flight of rare spirits and learn about the distilling process.",
    time: "night",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "pizza-by-the-slice-crawl",
    title: "Pizza by the Slice Crawl",
    blurb: "Grab single slices from 3 different pizzerias to crown the citys best crust.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "all-you-can-eat-sushi",
    title: "All-You-Can-Eat Sushi",
    blurb: "Test your limits at a high-end revolving or buffet sushi spot.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "matcha-pastry-break",
    title: "Matcha & Pastry Break",
    blurb: "Visit a Japanese tea house for ceremonial matcha and black sesame treats.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "seafood-shack-on-the-pier",
    title: "Seafood Shack on the Pier",
    blurb: "Eat fresh fish and chips out of butcher paper overlooking the marina.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "food-tour",
    title: "Food Tour",
    blurb: "Book a local walking tour exploring 4 neighborhood food spots with a guide.",
    time: "day",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "burgers-in-the-car",
    title: "Burgers in the Car",
    blurb: "Order drive-thru, park overlooking a view, and eat on dashboard trays.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "charcuterie-bar",
    title: "Charcuterie Bar",
    blurb: "Order a massive customized board of cured meats, pickles, and hard cheeses.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "cider-house-tour",
    title: "Cider House Tour",
    blurb: "Sip crisp flights of apple and pear cider at an orchard barn.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "teppanyaki-show",
    title: "Teppanyaki Show",
    blurb: "Watch a chef catch eggs in their hat and light fires right in front of your table.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "french-bistro-date",
    title: "French Bistro Date",
    blurb: "Share steak frites and red wine at a romantic, candlelit French spot.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "bagel-coffee-morning",
    title: "Bagel & Coffee Morning",
    blurb: "Walk to an artisan bagel shop and eat warm lox bagels on a bench.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "hot-pot-station",
    title: "Hot Pot Station",
    blurb: "Dip fresh meats and noodles into a bubbling table-side broth.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "late-night-slice-arcade",
    title: "Late-Night Slice & Arcade",
    blurb: "Eat a quick slice of pizza then hit a retro arcade bar.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "gourmet-hot-dog-stand",
    title: "Gourmet Hot Dog Stand",
    blurb: "Find a street cart serving specialty loaded sausages.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "secret-menu-hunting",
    title: "Secret Menu Hunting",
    blurb: "Research fast-food secret menus and order the most absurd items.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "smoothie-juice-bar-walk",
    title: "Smoothie & Juice Bar Walk",
    blurb: "Grab fresh green juices or acai bowls before a morning walk.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "authentic-taqueria",
    title: "Authentic Taqueria",
    blurb: "Eat traditional street tacos off paper plates with fresh lime and cilantro.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "gastropub-craft-night",
    title: "Gastropub Craft Night",
    blurb: "Order elevated pub food and try seasonal beers on tap.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "chocolate-boutique",
    title: "Chocolate Boutique",
    blurb: "Buy 4 luxury hand-crafted truffles to savor slowly.",
    time: "day",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "coffee-cupping-session",
    title: "Coffee Cupping Session",
    blurb: "Attend a local roasters coffee tasting to learn notes and origins.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "local-theater-play",
    title: "Local Theater Play",
    blurb: "Support community theater by buying tickets to a small stage play.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "comedy-club-night",
    title: "Comedy Club Night",
    blurb: "Grab a table at a local stand-up club for drinks and laughs.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "art-gallery-opening",
    title: "Art Gallery Opening",
    blurb: "Attend an evening gallery opening for free wine, cheese, and modern art.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "indie-cinema-movie",
    title: "Indie Cinema Movie",
    blurb: "Skip the multiplex and watch an indie or foreign film at a vintage theater.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "museum-after-dark",
    title: "Museum After Dark",
    blurb: "Visit a major science or history museum during special adult evening hours.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "live-jazz-bar",
    title: "Live Jazz Bar",
    blurb: "Sit in a moody, low-lit basement bar listening to live jazz solos.",
    time: "night",
    cost: "low",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "thrift-store-outfit-swap",
    title: "Thrift Store Outfit Swap",
    blurb: "Set a $15 limit each; pick out a ridiculous outfit for the other to wear on the date.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "symphony-orchestra",
    title: "Symphony Orchestra",
    blurb: "Dress up in black-tie attire for a classical concert night.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "antique-mall-hunting",
    title: "Antique Mall Hunting",
    blurb: "Browse endless aisles of vintage furniture, trinkets, and old photos.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "sip-paint-studio",
    title: "Sip & Paint Studio",
    blurb: "Take a guided canvas painting class with drinks in hand.",
    time: "night",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "pottery-wheel-class",
    title: "Pottery Wheel Class",
    blurb: "Channel your inner Ghost with a hands-on clay throwing workshop.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "used-bookstore-scavenger-hunt",
    title: "Used Bookstore Scavenger Hunt",
    blurb: "Browse a huge used bookstore; find each other a book you think they must read.",
    time: "day",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "live-piano-bar",
    title: "Live Piano Bar",
    blurb: "Sing along to request-driven dueling pianos.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "arcade-bar-barcade",
    title: "Arcade Bar Barcade",
    blurb: "Play retro pinball, Pac-Man, and Street Fighter with quarters and craft beer.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "outdoor-concert-festival",
    title: "Outdoor Concert Festival",
    blurb: "Bring lawn chairs to a free summer park concert.",
    time: "night",
    cost: "free",
    vibe: "social",
    location: "out",
  },
  {
    id: "glassblowing-demonstration",
    title: "Glassblowing Demonstration",
    blurb: "Watch artisans shape molten glass or take a beginner workshop.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "improv-comedy-show",
    title: "Improv Comedy Show",
    blurb: "Watch fast-paced unscripted theater where audience prompts rule the stage.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "ballet-opera",
    title: "Ballet Opera",
    blurb: "Experience a high-culture night out at an opera or ballet performance.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "record-store-browsing",
    title: "Record Store Browsing",
    blurb: "Flip through crates of vintage vinyl records and pick 1 album for home.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "observatory-planetarium",
    title: "Observatory Planetarium",
    blurb: "Watch a star projection show or look through massive telescopes.",
    time: "night",
    cost: "low",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "burlesque-show",
    title: "Burlesque Show",
    blurb: "Enjoy a cheeky, high-energy vintage dance and cabaret performance.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "open-mic-night",
    title: "Open Mic Night",
    blurb: "Watch brave local musicians, poets, and comics test new material at a cafe.",
    time: "night",
    cost: "free",
    vibe: "social",
    location: "out",
  },
  {
    id: "interactive-art-exhibit",
    title: "Interactive Art Exhibit",
    blurb: "Walk through an immersive digital art experience (like Van Gogh or Meow Wolf).",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "architectural-walking-tour",
    title: "Architectural Walking Tour",
    blurb: "Explore grand old buildings or historic homes in your city.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "graffiti-street-art-stroll",
    title: "Graffiti & Street Art Stroll",
    blurb: "Tour famous laneways and murals taking vibrant photos.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "drive-in-double-feature",
    title: "Drive-In Double Feature",
    blurb: "Park backwards, load the truck bed with blankets, and watch two films.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "library-date",
    title: "Library Date",
    blurb: "Visit a grand central library, find quiet corners, and write secret notes in book pages.",
    time: "day",
    cost: "free",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "live-poetry-slam",
    title: "Live Poetry Slam",
    blurb: "Experience raw, passionate spoken-word artists competing on stage.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "trivia-night-at-a-pub",
    title: "Trivia Night at a Pub",
    blurb: "Form a two-person team and test your random knowledge for bar tabs.",
    time: "night",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "modern-art-museum",
    title: "Modern Art Museum",
    blurb: "Argue over whether a plain white canvas is actually brilliant art.",
    time: "day",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "symphony-in-the-park",
    title: "Symphony in the Park",
    blurb: "Listen to an outdoor orchestra performing film scores under the stars.",
    time: "night",
    cost: "free",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "latin-dance-night",
    title: "Latin Dance Night",
    blurb: "Attend a Salsa/Bachata intro lesson followed by open social dancing.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "vintage-arcade",
    title: "Vintage Arcade",
    blurb: "Seek out an old-school ticket arcade and win cheap plastic rings.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "film-festival",
    title: "Film Festival",
    blurb: "Buy passes to watch short indie films at a local festival.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "ghost-tour",
    title: "Ghost Tour",
    blurb: "Walk dark historical alleys with a lantern-bearing guide telling haunted tales.",
    time: "night",
    cost: "low",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "car-show",
    title: "Car Show",
    blurb: "Walk through shiny vintage custom cars or classic auto showcases.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "shakespeare-in-the-park",
    title: "Shakespeare in the Park",
    blurb: "Watch an open-air theater production on a grassy hill.",
    time: "night",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "artisan-craft-fair",
    title: "Artisan Craft Fair",
    blurb: "Browse handmade jewelry, leather goods, and ceramics made by locals.",
    time: "day",
    cost: "free",
    vibe: "social",
    location: "out",
  },
  {
    id: "magic-show",
    title: "Magic Show",
    blurb: "Watch mind-bending sleight of hand at an intimate parlor magic venue.",
    time: "night",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "science-center-after-hours",
    title: "Science Center After Hours",
    blurb: "Play with interactive physics and space exhibits without kids around.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "open-studio-walk",
    title: "Open Studio Walk",
    blurb: "Tour local artists working studios during neighborhood art walks.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "outdoor-silent-cinema",
    title: "Outdoor Silent Cinema",
    blurb: "Wear headphones on a lawn watching classic 80s movies.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "circus-performance",
    title: "Circus Performance",
    blurb: "Watch breathtaking acrobatics, silk artists, and aerialists.",
    time: "night",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "lecture-ted-style-talk",
    title: "Lecture TED-style Talk",
    blurb: "Attend a fascinating public lecture by an author or scientist.",
    time: "night",
    cost: "low",
    vibe: "creative",
    location: "out",
  },
  {
    id: "book-launch",
    title: "Book Launch",
    blurb: "Go to an indie store book signing and listen to the author read excerpts.",
    time: "night",
    cost: "free",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "flea-market-hunting",
    title: "Flea Market Hunting",
    blurb: "Dig through boxes of old tools, cards, and vintage gear on a Sunday morning.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "cultural-center-festival",
    title: "Cultural Center Festival",
    blurb: "Experience traditional music, dance, and food at a community cultural fair.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "acoustic-coffeehouse-show",
    title: "Acoustic Coffeehouse Show",
    blurb: "Listen to a singer-songwriter with a guitar in an intimate setting.",
    time: "night",
    cost: "low",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "watch-a-taping",
    title: "Watch a Taping",
    blurb: "Sit in the live studio audience for a local TV show or podcast recording.",
    time: "day",
    cost: "free",
    vibe: "creative",
    location: "out",
  },
  {
    id: "rock-concert",
    title: "Rock Concert",
    blurb: "Stand close to the stage and get lost in loud, live guitar music.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "mini-golf-putt-putt",
    title: "Mini-Golf Putt-Putt",
    blurb: "Play 18 holes of mini-golf; loser buys the winner an ice cream.",
    time: "anytime",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "bowling-night",
    title: "Bowling Night",
    blurb: "Rent neon shoes, order greasy pitcher beer, and aim for strikes.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "go-kart-racing",
    title: "Go-Kart Racing",
    blurb: "Strap on helmets and race high-speed electric karts around a track.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "axe-throwing",
    title: "Axe Throwing",
    blurb: "Channel your inner lumberjack throwing axes at wooden targets.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "indoor-rock-climbing",
    title: "Indoor Rock Climbing",
    blurb: "Auto-belay or boulder together at a climbing gym.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "ice-skating",
    title: "Ice Skating",
    blurb: "Hold hands while trying not to fall on fresh ice.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "roller-skating-rink",
    title: "Roller Skating Rink",
    blurb: "Retro roller disco with strobe lights and 80s tunes.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "batting-cages",
    title: "Batting Cages",
    blurb: "Hit fastballs and slow-pitch softballs in protective cages.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "laser-tag",
    title: "Laser Tag",
    blurb: "Form a duo and battle other teams in a dark, fog-filled maze.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "escape-room",
    title: "Escape Room",
    blurb: "Work together to solve puzzles and escape a locked room in under 60 minutes.",
    time: "anytime",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "trampoline-park",
    title: "Trampoline Park",
    blurb: "Jump around on wall-to-wall trampolines and foam pits.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "driving-range",
    title: "Driving Range",
    blurb: "Hit a bucket of golf balls off elevated mats.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "topgolf-lounge",
    title: "Topgolf Lounge",
    blurb: "Rent a heated bay, hit microchipped golf balls, and order appetizers.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "billiards-pool",
    title: "Billiards Pool",
    blurb: "Play 8-ball in a classic wooden pool hall.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "ping-pong-bar",
    title: "Ping Pong Bar",
    blurb: "Play high-energy table tennis with craft drinks nearby.",
    time: "night",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "stand-up-paddleboard-yoga",
    title: "Stand-Up Paddleboard Yoga",
    blurb: "Try balancing on water while attempting basic poses.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "darts-at-a-pub",
    title: "Darts at a Pub",
    blurb: "Play a game of 501 or Cricket on traditional bristle dartboards.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "zip-lining",
    title: "Zip-Lining",
    blurb: "Glide through forest canopies on high-speed cables.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "tennis-pickleball",
    title: "Tennis Pickleball",
    blurb: "Grab rackets and play a friendly singles match at local courts.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "surf-lesson",
    title: "Surf Lesson",
    blurb: "Rent softboard foamies and try catching white-water waves together.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "shooting-range",
    title: "Shooting Range",
    blurb: "Try target practice with safety instructors at an indoor range.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "archery-class",
    title: "Archery Class",
    blurb: "Learn how to notch arrows and hit bullseyes with a recurve bow.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "snorkeling",
    title: "Snorkeling",
    blurb: "Put on masks and flippers to explore local reef or rocky coastline life.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "live-sporting-event",
    title: "Live Sporting Event",
    blurb: "Cheer on your local team from stadium seats with hot dogs.",
    time: "anytime",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "rent-a-tandem-bike",
    title: "Rent a Tandem Bike",
    blurb: "Test your teamwork on a bicycle built for two.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "ninja-warrior-gym",
    title: "Ninja Warrior Gym",
    blurb: "Try obstacle courses, warped walls, and rope swings.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "virtual-reality-lounge",
    title: "Virtual Reality Lounge",
    blurb: "Put on headsets and fight zombies or explore space together.",
    time: "anytime",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "outdoor-fitness-class",
    title: "Outdoor Fitness Class",
    blurb: "Join an open-air boot camp or park workout session.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "frisbee-golf",
    title: "Frisbee Golf",
    blurb: "Toss frisbees through park courses aiming for metal baskets.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "shuffleboard",
    title: "Shuffleboard",
    blurb: "Play traditional tabletop or floor shuffleboard at a vintage bar.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "kayaking-at-sunset",
    title: "Kayaking at Sunset",
    blurb: "Paddle along the shore as the sun dips below the horizon.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "go-for-a-jog",
    title: "Go for a Jog",
    blurb: "Run a scenic 5k path followed by fresh fruit smoothies.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "footy-soccer-kick",
    title: "Footy Soccer Kick",
    blurb: "Grab a ball and head to an empty oval for a kick-to-kick.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "squash-racquetball",
    title: "Squash Racquetball",
    blurb: "Burn high energy in an enclosed indoor court.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "rollercoaster-park",
    title: "Rollercoaster Park",
    blurb: "Ride the biggest thrill rides at a theme park.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "water-park-slides",
    title: "Water Park Slides",
    blurb: "Slide down speed chutes and float along lazy rivers.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "skatepark-watch",
    title: "Skatepark Watch",
    blurb: "Bring drinks and watch local skaters drop into bowl ramps.",
    time: "day",
    cost: "free",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "bocce-ball-in-the-park",
    title: "Bocce Ball in the Park",
    blurb: "Set up a lawn game on flat grass with cold drinks.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "boxing-gym-trial",
    title: "Boxing Gym Trial",
    blurb: "Take an introductory heavy-bag conditioning class.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "mountain-biking",
    title: "Mountain Biking",
    blurb: "Rent suspension bikes and tackle dirt trails.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "badminton-match",
    title: "Badminton Match",
    blurb: "Set up a lightweight net in the yard or park.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "cornhole-tournament",
    title: "Cornhole Tournament",
    blurb: "Play cornhole boards at a local brewery garden.",
    time: "day",
    cost: "low",
    vibe: "social",
    location: "out",
  },
  {
    id: "sledding-tobogganing",
    title: "Sledding Tobogganing",
    blurb: "Slide down snowy hills on winter snow days.",
    time: "day",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "tubing-on-snow",
    title: "Tubing on Snow",
    blurb: "Ride inflated inner tubes down managed resort lanes.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "horseback-riding",
    title: "Horseback Riding",
    blurb: "Guided trail ride through countryside or forest paths.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "jet-ski-rental",
    title: "Jet Ski Rental",
    blurb: "Zip across open water on a rented personal watercraft.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "tough-mudder-mud-run",
    title: "Tough Mudder Mud Run",
    blurb: "Train for and complete a fun, muddy obstacle race.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "table-football-foosball",
    title: "Table Football Foosball",
    blurb: "Fast-paced table soccer matches at a pub.",
    time: "night",
    cost: "free",
    vibe: "active",
    location: "out",
  },
  {
    id: "pedal-boat-rental",
    title: "Pedal Boat Rental",
    blurb: "Pedal around a park lake in a swan-shaped boat.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "sandboarding",
    title: "Sandboarding",
    blurb: "Slide down massive coastal sand dunes on wooden boards.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "couples-massage",
    title: "Couples Massage",
    blurb: "Book side-by-side Swedish or deep-tissue massages at a day spa.",
    time: "day",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "staycation-hotel-night",
    title: "Staycation Hotel Night",
    blurb: "Book a 1-night boutique hotel stay in your own city.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "helicopter-tour",
    title: "Helicopter Tour",
    blurb: "Take a scenic flight over your city or coastline.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "hot-air-balloon-ride",
    title: "Hot Air Balloon Ride",
    blurb: "Drift over valleys at sunrise followed by a champagne breakfast.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "thermal-mineral-baths",
    title: "Thermal Mineral Baths",
    blurb: "Soak in outdoor natural hot springs or mineral pools.",
    time: "anytime",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "glamping-night",
    title: "Glamping Night",
    blurb: "Rent a luxury bell tent with a real bed and fire pit.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "float-tank-session",
    title: "Float Tank Session",
    blurb: "Experience total sensory deprivation floating in Epsom salt tanks.",
    time: "day",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "sunset-sail",
    title: "Sunset Sail",
    blurb: "Book a spot on a catamaran or sailboat for evening drinks on the water.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "chauffeur-limo-ride",
    title: "Chauffeur Limo Ride",
    blurb: "Hire a car to drive you around town sipping champagne before dinner.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "private-chef-at-home",
    title: "Private Chef at Home",
    blurb: "Hire a chef to cook a 4-course dinner right in your kitchen.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "home",
  },
  {
    id: "fancy-hotel-lobby-drinks",
    title: "Fancy Hotel Lobby Drinks",
    blurb: "Sit by grand fireplaces in 5-star hotel lobbies ordering fancy cocktails.",
    time: "night",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "pedicures-together",
    title: "Pedicures Together",
    blurb: "Sit in massage chairs side-by-side getting pampered.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "cabana-rental",
    title: "Cabana Rental",
    blurb: "Rent a daybed by a luxury pool with cocktail service.",
    time: "day",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "fine-dining-tasting-menu",
    title: "Fine Dining Tasting Menu",
    blurb: "Indulge in a 7-course chefs menu with wine pairings.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "weekend-cabin-getaway",
    title: "Weekend Cabin Getaway",
    blurb: "Rent a quiet woodland cabin with a fireplace and wood-fired hot tub.",
    time: "anytime",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "perfume-cologne-crafting",
    title: "Perfume Cologne Crafting",
    blurb: "Visit a custom scent lab to blend bespoke fragrances for each other.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "infrared-sauna-ice-bath",
    title: "Infrared Sauna & Ice Bath",
    blurb: "Experience contrast therapy at a modern wellness clinic.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "private-movie-theater-rental",
    title: "Private Movie Theater Rental",
    blurb: "Rent out a small local screen room for just the two of you.",
    time: "anytime",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "champagne-picnic",
    title: "Champagne Picnic",
    blurb: "High-end charcuterie, strawberries, and French champagne on a silk throw.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "blowdry-suit-prep-night",
    title: "Blowdry & Suit Prep Night",
    blurb: "Get professionally styled before hitting an ultra-fancy gala or dinner.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "cryotherapy-session",
    title: "Cryotherapy Session",
    blurb: "Try sub-zero recovery chambers together for an adrenaline boost.",
    time: "day",
    cost: "low",
    vibe: "active",
    location: "out",
  },
  {
    id: "scenic-flight",
    title: "Scenic Flight",
    blurb: "Charter a small light-aircraft flight over local landmarks.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "private-wine-cellar-tour",
    title: "Private Wine Cellar Tour",
    blurb: "Dine inside an underground cellar surrounded by vintage bottles.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "luxury-car-rental",
    title: "Luxury Car Rental",
    blurb: "Rent a dream sports car or convertible for a 24-hour coastal drive.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "gondola-water-ride",
    title: "Gondola Water Ride",
    blurb: "Ride an authentic wooden gondola down river canals with a musician.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "bed-breakfast-weekend",
    title: "Bed & Breakfast Weekend",
    blurb: "Stay at a historic countryside inn with homemade hot breakfasts.",
    time: "anytime",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "seaplane-to-lunch",
    title: "Seaplane to Lunch",
    blurb: "Take a seaplane landing directly at a waterfront restaurant.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "blow-your-own-glass",
    title: "Blow Your Own Glass",
    blurb: "Craft custom cocktail glasses at an artisan furnace studio.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "head-massage-scalp-spa",
    title: "Head Massage Scalp Spa",
    blurb: "Book Japanese scalp treatment spa sessions.",
    time: "day",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "private-yurt-stay",
    title: "Private Yurt Stay",
    blurb: "Spend a night in an insulated yurt surrounded by wilderness.",
    time: "night",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "personal-stylist-shopping",
    title: "Personal Stylist Shopping",
    blurb: "Have a stylist pull outfits for you both at a department store.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "caviar-tasting",
    title: "Caviar Tasting",
    blurb: "Sample fine caviars paired with chilled vodka or champagne.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "exclusive-speakeasy-booking",
    title: "Exclusive Speakeasy Booking",
    blurb: "Reserve private booth seating behind secret velvet curtains.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "sunset-opera",
    title: "Sunset Opera",
    blurb: "Watch an open-air opera performance on a harbor foreshore.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "private-boat-charter",
    title: "Private Boat Charter",
    blurb: "Charter a small motorboat to explore hidden coves on your own.",
    time: "day",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "sound-bath-therapy",
    title: "Sound Bath Therapy",
    blurb: "Lay on mats while Tibetan singing bowls wash vibrational sound over you.",
    time: "night",
    cost: "low",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "equestrian-sunset-beach-ride",
    title: "Equestrian Sunset Beach Ride",
    blurb: "Ride horses along a tide line as the sun sets.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "luxury-train-dining",
    title: "Luxury Train Dining",
    blurb: "Eat 3 courses inside a restored 1920s dining train car traveling through valleys.",
    time: "day",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "bespoke-ring-making",
    title: "Bespoke Ring Making",
    blurb: "Attend a jewelry workshop to forge simple silver rings for each other.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "infinity-pool-sunset",
    title: "Infinity Pool Sunset",
    blurb: "Access a high-rise infinity pool overlooking a skyline at dusk.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "jazz-cruise",
    title: "Jazz Cruise",
    blurb: "Dine on a riverboat while listening to a live jazz band.",
    time: "night",
    cost: "splurge",
    vibe: "social",
    location: "out",
  },
  {
    id: "mystery-flight-trip",
    title: "Mystery Flight Trip",
    blurb: "Book a mystery weekend package where the destination is revealed at the airport.",
    time: "anytime",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
  {
    id: "luxury-seafood-tower",
    title: "Luxury Seafood Tower",
    blurb: "Order a 3-tier chilled lobster, crab, and oyster tower at a coastal restaurant.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "vip-concert-tickets",
    title: "VIP Concert Tickets",
    blurb: "Watch your favorite band from front-row seats or private box lounges.",
    time: "night",
    cost: "splurge",
    vibe: "active",
    location: "out",
  },
  {
    id: "high-altitude-dining",
    title: "High-Altitude Dining",
    blurb: "Eat at a revolving restaurant on the top floor of a skyscraper.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "night-spa-access",
    title: "Night Spa Access",
    blurb: "Soak in outdoor heated pools past midnight under quiet starry skies.",
    time: "night",
    cost: "splurge",
    vibe: "relaxed",
    location: "out",
  },
  {
    id: "private-museum-tour",
    title: "Private Museum Tour",
    blurb: "Hire a private guide to tour an art gallery after public doors close.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "champagne-tasting-class",
    title: "Champagne Tasting Class",
    blurb: "Learn the subtle differences between vintage French Champagnes.",
    time: "night",
    cost: "splurge",
    vibe: "spicy",
    location: "out",
  },
  {
    id: "lakeside-log-cabin",
    title: "Lakeside Log Cabin",
    blurb: "Disconnect completely with no Wi-Fi, wood stoves, and lake views.",
    time: "anytime",
    cost: "splurge",
    vibe: "cozy",
    location: "out",
  },
  {
    id: "the-yes-day",
    title: "The Yes Day",
    blurb: "One partner gets to say YES to every activity, meal, and request the other makes for 24 hours.",
    time: "day",
    cost: "splurge",
    vibe: "creative",
    location: "out",
  },
];

export function filterDateIdeas(filters: DateIdeaFilters): DateIdea[] {
  return DATE_IDEAS.filter((idea) => {
    if (filters.location !== "all" && idea.location !== filters.location) return false;
    if (filters.cost !== "all" && idea.cost !== filters.cost) return false;
    if (filters.vibe !== "all" && idea.vibe !== filters.vibe) return false;
    if (filters.time !== "all") {
      if (idea.time !== "anytime" && idea.time !== filters.time) return false;
    }
    return true;
  });
}

export function pickRandomDateIdea(
  filters: DateIdeaFilters,
  excludeId?: string | null
): DateIdea | null {
  const pool = filterDateIdeas(filters).filter((idea) => idea.id !== excludeId);
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)]!;
}

export function dateIdeaById(id: string): DateIdea | null {
  return DATE_IDEAS.find((idea) => idea.id === id) ?? null;
}
