export type DiscoverCategoryId =
  | "have-flirty"
  | "have-spicy"
  | "have-funny"
  | "have-bold"
  | "last-flirty"
  | "last-spicy"
  | "last-funny"
  | "last-bold"
  | "solo"
  | "prefs"
  | "taboo"
  | "memory"
  | "would-rather"
  | "dreams"
  | "fears"
  | "values"
  | "childhood"
  | "habits"
  | "us"
  | "existential"
  | "body"
  | "kinks"
  | "solo-tech"
  | "bedroom"
  | "risky"
  | "emotion"
  | "wild";

export type DiscoverQuestion = {
  id: string;
  prompt: string;
  category: DiscoverCategoryId;
};

type DiscoverRow = readonly [DiscoverCategoryId, string];

const BANK: readonly DiscoverRow[] = [
  ["have-flirty", "Have you ever caught yourself checking me out when you thought I wasn’t looking?"],
  ["have-flirty", "Have you ever gotten a crush on someone just because of the way they smelled?"],
  ["have-flirty", "Have you ever sent a text intended for someone else that was way too flirtatious?"],
  ["have-flirty", "Have you ever practiced kissing on your hand or a pillow?"],
  ["have-flirty", "Have you ever winked at a stranger just to see how they’d react?"],
  ["have-flirty", "Have you ever pretended to be cold just to get someone to put their arm around you?"],
  ["have-flirty", "Have you ever flirted your way out of a speeding ticket or bad situation?"],
  ["have-flirty", "Have you ever had a dream about someone in this room and never told them?"],
  ["have-flirty", "Have you ever worn an outfit specifically to get one person’s attention?"],
  ["have-flirty", "Have you ever intentionally \"accidentally\" brushed against someone you liked?"],
  ["have-flirty", "Have you ever flirted with someone just to make someone else jealous?"],
  ["have-flirty", "Have you ever gotten butterflies just from a simple text message?"],
  ["have-flirty", "Have you ever liked someone’s photo from three years ago while stalk-scrolling?"],
  ["have-flirty", "Have you ever kissed someone within five minutes of meeting them?"],
  ["have-flirty", "Have you ever used a pickup line so cheesy it actually worked?"],
  ["have-flirty", "Have you ever pretended to like a genre of music or movie just to impress a crush?"],
  ["have-flirty", "Have you ever given someone a fake phone number?"],
  ["have-flirty", "Have you ever tried to look cute while eating and failed miserably?"],
  ["have-flirty", "Have you ever had a crush on a fictional cartoon character?"],
  ["have-flirty", "Have you ever written a love letter or poem that you were too scared to send?"],
  ["have-flirty", "Have you ever accidentally said \"I love you\" to someone too early?"],
  ["have-flirty", "Have you ever worn matching underwear on purpose just in case?"],
  ["have-flirty", "Have you ever smiled at your phone so hard your face hurt?"],
  ["have-flirty", "Have you ever bitten your lip while looking at someone to be suggestive?"],
  ["have-flirty", "Have you ever secretly recorded a voice note to hear how your voice sounds when you flirt?"],
  ["have-spicy", "Have you ever sent a spicy photo and immediately regretted it?"],
  ["have-spicy", "Have you ever gotten caught doing something intimate in a semi-public place?"],
  ["have-spicy", "Have you ever had a naughty dream about a coworker or friend?"],
  ["have-spicy", "Have you ever lied about your \"number\" when asked?"],
  ["have-spicy", "Have you ever bought lingerie or special underwear just for a single night?"],
  ["have-spicy", "Have you ever been hooked up with someone whose name you couldn't remember the next morning?"],
  ["have-spicy", "Have you ever used food in the bedroom in a way that got messy?"],
  ["have-spicy", "Have you ever played a strip game (poker, truth or dare) and lost on purpose?"],
  ["have-spicy", "Have you ever kissed someone in an elevator while the doors were moving?"],
  ["have-spicy", "Have you ever had a secret hookup that absolutely nobody else knows about?"],
  ["have-spicy", "Have you ever sent a risky text to the wrong group chat?"],
  ["have-spicy", "Have you ever made out in the back row of a movie theater?"],
  ["have-spicy", "Have you ever owned a toy that you hid deep inside your luggage while traveling?"],
  ["have-spicy", "Have you ever been walked in on during a private moment?"],
  ["have-spicy", "Have you ever walked in on your parents or roommates at the worst possible time?"],
  ["have-spicy", "Have you ever tried a position from a guide and ended up laughing or hurting yourself?"],
  ["have-spicy", "Have you ever sent a voice note describing what you wanted to do to someone later?"],
  ["have-spicy", "Have you ever kissed someone under water in a swimming pool or hot tub?"],
  ["have-spicy", "Have you ever taken a naughty picture in a public bathroom mirror?"],
  ["have-spicy", "Have you ever stayed up until sunrise purely doing \"bedroom cardio\"?"],
  ["have-spicy", "Have you ever role-played with accents or fake names?"],
  ["have-spicy", "Have you ever had a wild encounter outdoors under the stars?"],
  ["have-spicy", "Have you ever worn something scandalous under regular clothes just for the thrill?"],
  ["have-spicy", "Have you ever accidentally left a mark on someone that they had to cover up the next day?"],
  ["have-spicy", "Have you ever whispered something so dirty to someone that it made them blush instantly?"],
  ["have-funny", "Have you ever laughed so hard while kissing that you snorted on the other person?"],
  ["have-funny", "Have you ever fallen off the bed during a romantic moment?"],
  ["have-funny", "Have you ever forgotten someone's name mid-makeout session?"],
  ["have-funny", "Have you ever tried to be sexy and ended up knocking something over and breaking it?"],
  ["have-funny", "Have you ever had your stomach make a loud, monstrous growl during a quiet, intimate moment?"],
  ["have-funny", "Have you ever gotten a cramp mid-action and had to freeze completely?"],
  ["have-funny", "Have you ever accidentally hit someone in the face while trying to remove clothes dramatically?"],
  ["have-funny", "Have you ever faked knowing how to dance just to get close to someone at a club?"],
  ["have-funny", "Have you ever gotten stuck inside a piece of clothing while trying to take it off enticingly?"],
  ["have-funny", "Have you ever lied about your age or job just to sound more interesting on a date?"],
  ["have-funny", "Have you ever had a pet sit at the end of the bed and stare at you during an intimate moment?"],
  ["have-funny", "Have you ever accidentally sent an embarrassing voice note of you singing to your crush?"],
  ["have-funny", "Have you ever pretended to get a fake call to escape a terrible date?"],
  ["have-funny", "Have you ever ordered a huge meal on a first date and eaten it like an animal without caring?"],
  ["have-funny", "Have you ever dropped your phone on your face while texting your crush in bed?"],
  ["have-funny", "Have you ever tried to do a romantic slow-motion walk and tripped?"],
  ["have-funny", "Have you ever gotten lipstick all over your face and didn't realize until you saw a mirror?"],
  ["have-funny", "Have you ever spit on someone by accident while talking passionately?"],
  ["have-funny", "Have you ever accidentally called a partner by your ex's name?"],
  ["have-funny", "Have you ever worn two different shoes on a date because you were rushing to look good?"],
  ["have-funny", "Have you ever sneezed on someone mid-hug?"],
  ["have-funny", "Have you ever gotten your hair snagged in someone’s zipper or buttons?"],
  ["have-funny", "Have you ever lied about having seen a movie just so someone would invite you to watch it?"],
  ["have-funny", "Have you ever Googled \"how to flirt\" before going out?"],
  ["have-funny", "Have you ever fallen asleep while someone was trying to make out with you?"],
  ["have-bold", "Have you ever skinny-dipped in an ocean, lake, or public pool?"],
  ["have-bold", "Have you ever had a one-night stand in a foreign country?"],
  ["have-bold", "Have you ever kissed more than one person in the same night?"],
  ["have-bold", "Have you ever joined the \"Mile High Club\"?"],
  ["have-bold", "Have you ever done something risky in a car parked in a public spot?"],
  ["have-bold", "Have you ever sent a spicy snap/text while sitting at a family dinner?"],
  ["have-bold", "Have you ever kissed a total stranger on New Year’s Eve just because?"],
  ["have-bold", "Have you ever snuck out of a house through a window after a late-night visit?"],
  ["have-bold", "Have you ever had a spontaneous hookup in a changing room or fitting room?"],
  ["have-bold", "Have you ever let someone write or draw on your body with a pen or lipstick?"],
  ["have-bold", "Have you ever kissed someone while standing under a waterfall or in heavy rain?"],
  ["have-bold", "Have you ever played a game of truth or dare that went way further than expected?"],
  ["have-bold", "Have you ever had an intense flirtation using only eye contact across a crowded room?"],
  ["have-bold", "Have you ever made out on a rooftop?"],
  ["have-bold", "Have you ever sent a message saying \"I'm not wearing anything\" when you actually were?"],
  ["have-bold", "Have you ever flirted with someone to get a free drink or extra food?"],
  ["have-bold", "Have you ever kissed someone whose language you didn’t even speak?"],
  ["have-bold", "Have you ever stayed in a hotel room for 24 hours straight without leaving the bed?"],
  ["have-bold", "Have you ever made a bet involving a spicy consequence?"],
  ["have-bold", "Have you ever had a romantic encounter on a beach and regretted the sand later?"],
  ["have-bold", "Have you ever let someone feed you fruit or dessert by hand?"],
  ["have-bold", "Have you ever intentionally worn an unbuttoned shirt/low-cut top to drive someone crazy?"],
  ["have-bold", "Have you ever done something bold just to prove a point to a crush?"],
  ["have-bold", "Have you ever had a romantic moment on a balcony?"],
  ["have-bold", "Have you ever looked at someone and thought, \"I am definitely going to kiss them tonight\"?"],
  ["last-flirty", "When was the last time you stalked a crush’s social media all the way back to 2018?"],
  ["last-flirty", "When was the last time you spent more than 20 minutes picking out an outfit for one specific person?"],
  ["last-flirty", "When was the last time your heart skipped a beat when a specific name popped up on your phone?"],
  ["last-flirty", "When was the last time you flirted with a cashier, bartender, or barista?"],
  ["last-flirty", "When was the last time you bit your lip while thinking about someone?"],
  ["last-flirty", "When was the last time you got a compliment that made you turn bright red?"],
  ["last-flirty", "When was the last time you rehearsed a conversation in the mirror before seeing someone?"],
  ["last-flirty", "When was the last time you intentionally double-texted someone because you couldn't wait?"],
  ["last-flirty", "When was the last time you gave someone \"the eyes\" from across a room?"],
  ["last-flirty", "When was the last time you stayed up past 3 AM just texting or talking to someone you like?"],
  ["last-flirty", "When was the last time you dressed up super cute with nowhere to go?"],
  ["last-flirty", "When was the last time you caught someone blatantly checking you out?"],
  ["last-flirty", "When was the last time you played hard to get on purpose?"],
  ["last-flirty", "When was the last time you used a romantic song to signal your feelings on your story/status?"],
  ["last-flirty", "When was the last time you felt instant chemistry with a complete stranger?"],
  ["last-flirty", "When was the last time you left a subtle hint for someone that went completely over their head?"],
  ["last-flirty", "When was the last time you winked at someone in real life?"],
  ["last-flirty", "When was the last time you initiated physical contact first (a touch on the arm, a hug, a kiss)?"],
  ["last-flirty", "When was the last time you got jealous over something tiny?"],
  ["last-flirty", "When was the last time you smelled a piece of clothing because it reminded you of someone?"],
  ["last-flirty", "When was the last time you posted a picture purely as \"bait\" for one person to view?"],
  ["last-flirty", "When was the last time you got butterfly chills down your spine from a simple touch?"],
  ["last-flirty", "When was the last time you blushed so hard you had to look away?"],
  ["last-flirty", "When was the last time you made the first move?"],
  ["last-flirty", "When was the last time you fantasized about a romantic weekend getaway?"],
  ["last-spicy", "When was the last time you sent a spicy preview text like \"Wait till you see what I'm wearing\"?"],
  ["last-spicy", "When was the last time you had a completely wild dream about someone sitting near you?"],
  ["last-spicy", "When was the last time you bought something scandalous online?"],
  ["last-spicy", "When was the last time you gave or received a massage that turned into something more?"],
  ["last-spicy", "When was the last time you hooked up somewhere that wasn't a bed?"],
  ["last-spicy", "When was the last time you deleted a message thread so nobody else would read it?"],
  ["last-spicy", "When was the last time you took a photo you'd never show your parents?"],
  ["last-spicy", "When was the last time you had a session so intense you woke up sore the next morning?"],
  ["last-spicy", "When was the last time you whispered a filthy idea into someone’s ear in public?"],
  ["last-spicy", "When was the last time you tried a new position or trick you read about online?"],
  ["last-spicy", "When was the last time you got caught in the middle of a passionate moment?"],
  ["last-spicy", "When was the last time you had a secret fling that nobody knew about?"],
  ["last-spicy", "When was the last time you used handcuffs, ribbons, or blindfolds?"],
  ["last-spicy", "When was the last time you sent a risky text from work or school?"],
  ["last-spicy", "When was the last time you made out so hard your lips felt swollen the next day?"],
  ["last-spicy", "When was the last time you took a long, hot shower with someone else?"],
  ["last-spicy", "When was the last time you couldn't keep your hands to yourself in a car?"],
  ["last-spicy", "When was the last time you played a game like Spin the Bottle or Strip Poker?"],
  ["last-spicy", "When was the last time you gave someone a hickey (or got one)?"],
  ["last-spicy", "When was the last time you did something naughty specifically because it was forbidden?"],
  ["last-spicy", "When was the last time you left your underwear on the floor of someone else's house?"],
  ["last-spicy", "When was the last time you had a late-night spontaneous visit from a crush?"],
  ["last-spicy", "When was the last time you logged into an app just looking for a quick encounter?"],
  ["last-spicy", "When was the last time you engaged in dirty talk that surprised even yourself?"],
  ["last-spicy", "When was the last time you couldn't focus on work because you were thinking about last night?"],
  ["last-funny", "When was the last time you tried to look effortless and ended up looking ridiculous?"],
  ["last-funny", "When was the last time you panicked because someone unlocked your phone with your photo gallery open?"],
  ["last-funny", "When was the last time you accidentally liked an old photo while creeping on someone’s page?"],
  ["last-funny", "When was the last time you laughed mid-kiss because of a weird noise?"],
  ["last-funny", "When was the last time you sent a text, realized it sounded creepy, and tried to fix it?"],
  ["last-funny", "When was the last time you got stuck in a tight outfit and needed help getting out?"],
  ["last-funny", "When was the last time you tried to be mysterious and just came across as weird?"],
  ["last-funny", "When was the last time you snored or drooled while sleeping next to someone you wanted to impress?"],
  ["last-funny", "When was the last time you choked on your own spit while trying to say something cool?"],
  ["last-funny", "When was the last time you Googled someone before a first date to make sure they weren't crazy?"],
  ["last-funny", "When was the last time you lied about liking a terrible movie just to stay on a date longer?"],
  ["last-funny", "When was the last time you made a weird face while trying to look sexy in a photo?"],
  ["last-funny", "When was the last time you got food stuck in your teeth during a romantic dinner?"],
  ["last-funny", "When was the last time you accidentally texted your parent something meant for your crush?"],
  ["last-funny", "When was the last time you wore uncomfortable clothes purely for aesthetic reasons and regretted it immediately?"],
  ["last-funny", "When was the last time you had a date so bad you had to laugh about it right after?"],
  ["last-funny", "When was the last time you tried to do a romantic gesture and it went completely wrong?"],
  ["last-funny", "When was the last time you pretended to understand a joke you didn't get just to fit in?"],
  ["last-funny", "When was the last time you bumped heads with someone while trying to go in for a kiss?"],
  ["last-funny", "When was the last time you got nervous and talked way too fast or way too much on a date?"],
  ["last-funny", "When was the last time you checked your breath in your hand 50 times in one hour?"],
  ["last-funny", "When was the last time you accidentally spilled a drink all over yourself while trying to look smooth?"],
  ["last-funny", "When was the last time you had an awkward high-five/hug combo moment with someone you liked?"],
  ["last-funny", "When was the last time you used a cheesy line as a joke that actually ended up working?"],
  ["last-funny", "When was the last time you checked your hair in a car window only to realize someone was sitting inside?"],
  ["last-bold", "When was the last time you went out with zero intent to hook up and ended up staying out all night?"],
  ["last-bold", "When was the last time you kissed someone under starry skies?"],
  ["last-bold", "When was the last time you initiated a risky conversation about what you *really* want in bed?"],
  ["last-bold", "When was the last time you took a midnight swim with no clothes on?"],
  ["last-bold", "When was the last time you made out in a venue or building after hours?"],
  ["last-bold", "When was the last time you kissed someone you knew you shouldn't be kissing?"],
  ["last-bold", "When was the last time you asked someone out face-to-face without texting first?"],
  ["last-bold", "When was the last time you spent an entire Sunday in bed with another person?"],
  ["last-bold", "When was the last time you bought something spontaneous just to turn someone on?"],
  ["last-bold", "When was the last time you flirted with someone significantly older or younger than you?"],
  ["last-bold", "When was the last time you had a romantic moment in the rain?"],
  ["last-bold", "When was the last time you let someone control your outfit for the night?"],
  ["last-bold", "When was the last time you played a game of Truth or Dare with real stakes?"],
  ["last-bold", "When was the last time you took a spontaneous road trip with a crush?"],
  ["last-bold", "When was the last time you kissed someone on a dance floor surrounded by people?"],
  ["last-bold", "When was the last time you ordered room service after an intense night?"],
  ["last-bold", "When was the last time you gave a lap dance or received one?"],
  ["last-bold", "When was the last time you had a secret signal with someone to mean \"let's leave right now\"?"],
  ["last-bold", "When was the last time you sent a voice recording whispering something daring?"],
  ["last-bold", "When was the last time you confessed a secret desire to someone?"],
  ["last-bold", "When was the last time you kissed someone on a balcony overlooking a city?"],
  ["last-bold", "When was the last time you wore something completely out of your comfort zone to feel attractive?"],
  ["last-bold", "When was the last time you locked a door specifically to have 10 quick minutes alone with someone?"],
  ["last-bold", "When was the last time you stole a kiss when nobody was looking?"],
  ["last-bold", "When was the last time you looked at someone and realized you were completely smitten?"],
  ["solo", "When was the last time you played with yourself, and what were you watching or thinking about?"],
  ["solo", "Do you have a favorite toy or item you use when you're alone that I've never seen?"],
  ["solo", "What is a specific adult video genre or tag you search for that you’d be embarrassed if anyone found out?"],
  ["solo", "How often do you think about intimacy during a normal workday?"],
  ["solo", "Have you ever touched yourself in a place where you could have easily been caught?"],
  ["solo", "What is a secret fantasy you have about us that you’ve been too shy to describe in detail?"],
  ["solo", "Have you ever gotten turned on by someone completely random or inappropriate in public?"],
  ["solo", "Do you prefer morning, afternoon, or late-night encounters, and why?"],
  ["solo", "What is a sexual desire or kink you’ve always been curious about but have never actually tried?"],
  ["solo", "Have you ever edged yourself for hours just to make the finish stronger?"],
  ["solo", "What is the dirtiest photo or video currently saved on your phone, and where is it hidden?"],
  ["solo", "Have you ever touched yourself while on the phone or texting with me without telling me?"],
  ["prefs", "How do you actually feel about anal sex—do you love it, curious about it, or dislike it?"],
  ["prefs", "Do you prefer giving or receiving oral, and what’s your favorite technique for it?"],
  ["prefs", "How do you feel about swallowing versus finishing on skin or clothes?"],
  ["prefs", "Do you like hair pulling, biting, or light spanking, or do you prefer things soft and gentle?"],
  ["prefs", "What is your absolute favorite position when you want to finish as fast as possible?"],
  ["prefs", "What position allows you to feel the deepest emotional or physical connection?"],
  ["prefs", "How do you feel about being dominant versus being completely submissive in bed?"],
  ["prefs", "Do you like intense eye contact during intimate moments, or does it make you self-conscious?"],
  ["prefs", "What is a piece of lingerie, outfit, or style of clothing that instantly turns you on?"],
  ["prefs", "How do you feel about playing with temperature (ice cubes, warm wax, hot oils)?"],
  ["prefs", "Do you like dirty talk, and what is the exact word or phrase that turns you on the most?"],
  ["prefs", "Have you ever wanted to try using blindfolds, light restraints, or cuffs with me?"],
  ["prefs", "How do you feel about mirror play or watching us in front of a mirror?"],
  ["taboo", "What is the most public or risky place you’ve ever had a hookup or touched someone?"],
  ["taboo", "Have you ever wanted to make out or do something risky in a parked car at night?"],
  ["taboo", "How do you feel about exhibitionism or the idea of someone accidentally hearing us?"],
  ["taboo", "Have you ever recorded a video or taken photos during an intimate moment?"],
  ["taboo", "What is your stance on roleplay—is there a specific scenario or persona you’d want to try?"],
  ["taboo", "Have you ever had a dream or secret thought about involving a third person or swapping?"],
  ["taboo", "What is a boundary you used to have that you’d now be willing to cross for the right thrill?"],
  ["taboo", "Have you ever worn something revealing or quick-access under regular clothes in public?"],
  ["taboo", "What is the wildest place in our home you’ve wanted to use besides the bed?"],
  ["taboo", "Do you like the idea of quickies in places where we might get interrupted?"],
  ["memory", "What was the exact moment in our relationship where you felt the strongest physical attraction to me?"],
  ["memory", "Have you ever faked an orgasm or exaggerated your reaction with me just to wrap things up?"],
  ["memory", "Is there a specific encounter we had in the past that you still replay in your head when you're alone?"],
  ["memory", "What is something I do in bed that you secretly wish I would do way more often?"],
  ["memory", "Is there anything we currently do during intimacy that you actually don't enjoy that much?"],
  ["memory", "What is the longest you’ve ever gone without any intimate release, and how did it affect you?"],
  ["memory", "Have you ever felt turned on right after an argument or during an intense emotional moment?"],
  ["memory", "What was your very first impression of my body the first time we took our clothes off together?"],
  ["memory", "Have you ever compared our physical chemistry to a past partner, and how do we stack up?"],
  ["memory", "What is one area of your body you feel self-conscious about during intimacy that you wish I’d praise more?"],
  ["would-rather", "Would you rather have a passionate, slow 2-hour session or a rough, intense 5-minute quickie right now?"],
  ["would-rather", "Would you rather control everything I do in bed for a night, or let me have total control over you?"],
  ["would-rather", "Would you rather send spicy photos back and forth all day at work or save it all for a surprise tonight?"],
  ["would-rather", "Would you rather spend a whole night exploring only oral and touch, or stick strictly to full intercourse?"],
  ["would-rather", "If we had 15 minutes completely alone in a locked room right now, what’s the first thing you’d take off me?"],
  ["dreams", "What is one goal or dream you’ve never told anyone about because you’re afraid they’ll laugh?"],
  ["dreams", "If you could live a completely secret double life without any consequences, what would you do?"],
  ["dreams", "What is something you secretly wish I would do in our relationship without you having to ask?"],
  ["dreams", "What is a fantasy about your future self that you rarely admit out loud?"],
  ["dreams", "What is a life path you almost took that you still secretly wonder \"what if\" about?"],
  ["dreams", "Is there a lifestyle or career you secretly envy in other people?"],
  ["dreams", "What is something on your bucket list that feels a little too wild or embarrassing to tell most people?"],
  ["dreams", "If you could press a button and instantly master one skill or talent in secret, what would it be?"],
  ["dreams", "What is something you want to experience at least once before you die, no matter how taboo or unconventional?"],
  ["dreams", "What is a secret standard or expectation you hold yourself to that nobody else knows about?"],
  ["dreams", "If you were guaranteed never to get caught, what rule or law would you break just for the thrill?"],
  ["dreams", "What is a place in the world you secretly dream of running away to when life gets overwhelming?"],
  ["dreams", "What is something romantic or thoughtful you’ve always wanted a partner to do for you?"],
  ["dreams", "What is a skill or topic you’re secretly super interested in but haven't pursued yet?"],
  ["dreams", "What is one thing you hope people say about you when you're not in the room?"],
  ["fears", "What is an insecurity you have that you try really hard to hide from the world?"],
  ["fears", "What is your absolute biggest fear about growing old?"],
  ["fears", "What is something about your personality or behavior that you secretly dislike?"],
  ["fears", "What is a memory from your past that still makes you cringe or lie awake at night?"],
  ["fears", "What is a fear about our relationship or future together that you haven't brought up?"],
  ["fears", "When was the last time you felt truly lonely, and why?"],
  ["fears", "What is a situation or environment that makes you feel instantly self-conscious?"],
  ["fears", "What is a flaw you see in yourself that you worry might make you hard to love long-term?"],
  ["fears", "Have you ever felt like an \"imposter\" in your own life or career? When?"],
  ["fears", "What is something someone said to you years ago that hurt so much you still remember it perfectly?"],
  ["fears", "What is something you’re afraid you’ll never quite figure out or achieve in life?"],
  ["fears", "What is a boundary or boundary-crossing from your past that you never spoke up about?"],
  ["fears", "What is the hardest lesson a previous relationship taught you that still affects you today?"],
  ["fears", "What is a secret worry you have about how other people perceive you?"],
  ["fears", "What is a situation where you pretended to be confident, but were actually terrified inside?"],
  ["values", "What is a belief or opinion you hold that you keep quiet about because it's controversial?"],
  ["values", "What is something most people consider important or meaningful that you secretly don't care about at all?"],
  ["values", "What is a red flag in a person or relationship that you secretly overlook if you like them enough?"],
  ["values", "What is a harsh truth about life or human nature that you quietly accept?"],
  ["values", "Have you ever cut someone out of your life silently without giving them an explanation?"],
  ["values", "What is a petty reason you’ve secretly judged someone or stopped liking them?"],
  ["values", "What is something you think most people are pretending to enjoy just to fit in?"],
  ["values", "If you could change one thing about the way you were raised, what would it be?"],
  ["values", "What is an unwritten rule in society that you think is completely ridiculous?"],
  ["values", "What is a compliment you’ve received that felt fake or hollow to you?"],
  ["values", "Do you secretly think you’re better than average at something specific, even if you stay humble?"],
  ["values", "What is a popular moral or ethical debate where your true stance might surprise people?"],
  ["values", "What is a habit or behavior in close friends that you quietly tolerate but secretly hate?"],
  ["values", "What is something you feel people constantly misunderstand or get wrong about you?"],
  ["values", "What is the most dishonest thing you’ve ever done to protect someone’s feelings (or your own)?"],
  ["childhood", "What was your most prized secret possession growing up that nobody else was allowed to touch?"],
  ["childhood", "What is a lie you told your parents as a kid/teenager that they still don't know the truth about?"],
  ["childhood", "What was your favorite imaginary world, friend, or scenario as a child?"],
  ["childhood", "What is a childhood memory that feels insignificant to others, but secretly shaped who you are today?"],
  ["childhood", "What is a habit or fear you picked up from your childhood home that you're still trying to unlearn?"],
  ["childhood", "Did you have a secret crush on a teacher, friend's parent, or unexpected person growing up?"],
  ["childhood", "What is something embarrassing you used to collect or do in private when you were younger?"],
  ["childhood", "What was a moment in your youth where you felt completely misunderstood by everyone around you?"],
  ["childhood", "What is a rule you broke as a teenager just to feel independent or rebellious?"],
  ["childhood", "What is a piece of advice your parents gave you that you secretly rejected at the time (or still do)?"],
  ["childhood", "What was your most dramatic, secret teenage phase or subculture interest?"],
  ["childhood", "Did you ever write a diary or journal entry that you destroyed so no one would ever read it?"],
  ["childhood", "What was a hardship your family faced growing up that you didn't fully understand until you were older?"],
  ["childhood", "What was your favorite comfort activity as a kid when you were sad or overwhelmed?"],
  ["childhood", "What is a tradition or memory from your childhood you secretly want to recreate in your adult life?"],
  ["habits", "What is a weird or unusual habit you only do when you are completely alone at home?"],
  ["habits", "What is a guilty pleasure TV show, movie, or song you love but wouldn't display on your profile?"],
  ["habits", "What is a bizarre food combination or snack you secretly love eating?"],
  ["habits", "Have you ever pretended to be sick or busy just to stay home and do absolutely nothing?"],
  ["habits", "What is something you regularly Google or search for in incognito mode?"],
  ["habits", "Do you ever have full arguments or conversations out loud with yourself when no one is around?"],
  ["habits", "What is a petty or silly thing you do when you’re mad at someone that they never notice?"],
  ["habits", "What is a piece of media (book, game, video) that has made you cry completely in secret?"],
  ["habits", "What is an unusual object or item you keep for purely emotional or sentimental reasons?"],
  ["habits", "Do you have a secret \"lucky\" ritual, superstition, or habit before big events?"],
  ["habits", "What is something you inspect or over-analyze about yourself in the mirror when alone?"],
  ["habits", "Have you ever secretly re-gifted something or thrown away a gift you pretended to love?"],
  ["habits", "What is a weird rabbit hole on the internet you’ve spent hours researching?"],
  ["habits", "Do you ever secretly rehearse small interactions (like ordering food or making a call) before doing them?"],
  ["habits", "What is a comfort routine you turn to when you feel completely burnt out?"],
  ["us", "What was your exact, unfiltered first impression of me the very first time we met?"],
  ["us", "What is a tiny, subtle gesture I do that secretly makes you fall for me all over again?"],
  ["us", "Is there a moment in our relationship where you felt closer to me than ever before?"],
  ["us", "What is a conversation we haven't had yet that you are secretly waiting for us to have?"],
  ["us", "Have you ever had a secret fear about us that was resolved without me knowing?"],
  ["us", "What is one thing about my personality that you think balances you out the most?"],
  ["us", "Is there a habit of mine that you secretly find adorable, even if it's slightly strange?"],
  ["us", "What was a moment where I genuinely surprised you or flipped your expectations?"],
  ["us", "What is something you love about how we interact when it's just the two of us in private?"],
  ["us", "Is there a secret code word, gesture, or dynamic you wish we had between us in public?"],
  ["us", "What is a compliment I gave you that stayed with you long after I said it?"],
  ["us", "What is something you feel our relationship has healed or improved in you?"],
  ["us", "What is a boundary or preference you were nervous to tell me about at first?"],
  ["us", "If you had to describe our connection using a single private memory, which one would it be?"],
  ["us", "What is one promise you want us to make to each other that we haven't formally spoken yet?"],
  ["existential", "If you could ask a crystal ball one absolute truth about your future, what would you ask?"],
  ["existential", "What is a life lesson you had to learn the absolute hard way?"],
  ["existential", "What do you think is your personal \"blind spot\" in life that others see but you miss?"],
  ["existential", "If you could fix one regret from your past without changing where you are today, what would it be?"],
  ["existential", "What is a defining moment in your life that completely changed your perspective on everything?"],
  ["existential", "When do you feel most authentically like yourself, with no masks or pretenses?"],
  ["existential", "What is something you feel you owe yourself an apology for?"],
  ["existential", "What is a secret belief you have about why things happen the way they do in life?"],
  ["existential", "What is a legacy or feeling you want to leave behind in the lives of the people who love you?"],
  ["existential", "If you could hear the complete, unedited truth about any event in history or your own life, what would you pick?"],
  ["body", "What is your absolute favorite part of my body to touch, lick, or kiss?"],
  ["body", "What is one specific spot on your body that drives you crazy when I touch it, but I don't give enough attention to?"],
  ["body", "How do you feel about heavy breathing or groaning—does loud noise turn you on or distract you?"],
  ["body", "Do you like intense, heavy kissing throughout the whole act, or just during foreplay?"],
  ["body", "How do you feel about oral sex before showering versus after a long day?"],
  ["body", "What texture or sensation turns you on the most (e.g., silk, leather, oil, bare skin, teeth)?"],
  ["body", "Do you enjoy having your nipples sucked, bitten, or played with, or are they too sensitive?"],
  ["body", "What is your opinion on butt stuff during regular intimacy (like a stray finger, rimming, or massage)?"],
  ["body", "How do you feel about taste—do you genuinely enjoy the taste of my body fluids?"],
  ["body", "Do you like it when I leave visible marks on you (bruises, scratches, hickeys), or do you prefer to keep it hidden?"],
  ["body", "How do you feel about hair—do you prefer completely smooth, trimmed, or natural down there?"],
  ["body", "What speed do you prefer most: slow and deep grinding, or fast and hard thrusting?"],
  ["body", "Have you ever gotten turned on just by watching me get dressed or put on lotion?"],
  ["body", "How do you feel about saliva or lube—do you like things super wet and slippery, or tighter and drier?"],
  ["body", "Do you like having your hands pinned down above your head?"],
  ["kinks", "If you could control me like a remote control for 30 minutes in bed, what order of acts would you press?"],
  ["kinks", "How do you feel about degradation versus extreme praise (e.g., being called \"good girl/boy\" vs. dirty insults)?"],
  ["kinks", "Have you ever had a fantasy about being caught by a stranger through a window or open door?"],
  ["kinks", "Do you ever think about someone else while touching yourself or during intimacy with me?"],
  ["kinks", "What is a kink you think is super hot in theory, but you’re afraid might be awkward in real life?"],
  ["kinks", "How do you feel about impact play (slapping cheeks, spanking hard, or whip/paddles)?"],
  ["kinks", "Have you ever wanted to try bondage—being tied up so tightly you can't move at all?"],
  ["kinks", "What is your secret opinion on thongs or crotchless underwear?"],
  ["kinks", "Have you ever wanted to use a blindfold and earmuffs so you are completely deprived of your senses?"],
  ["kinks", "How do you feel about edge-play with choking/breath play—does light throat pressure turn you on?"],
  ["kinks", "Have you ever wished I was more aggressive or forceful in pursuing you?"],
  ["kinks", "Do you like the idea of \"overstimulation\"—continuing to touch or play with you right after you finish?"],
  ["kinks", "Have you ever had a fantasy about public exposure, like wearing a remote-controlled toy in a restaurant?"],
  ["kinks", "What is the most taboo adult category you’ve ever stumbled upon and secretly enjoyed?"],
  ["kinks", "How do you feel about roleplay involving power dynamics (e.g., boss/employee, doctor/patient)?"],
  ["solo-tech", "How many times a week do you touch yourself when I am not around?"],
  ["solo-tech", "What is the weirdest place in your house or apartment where you’ve finished solo?"],
  ["solo-tech", "Do you ever read erotic written stories or listen to audio pornography, or do you only watch video?"],
  ["solo-tech", "What time of day are you at your absolute horniest?"],
  ["solo-tech", "Have you ever taken an explicit video of yourself just to watch it back later?"],
  ["solo-tech", "Have you ever used an everyday household object as a toy because you didn't have one nearby?"],
  ["solo-tech", "If I unlocked your phone right now, what would be the most embarrassing thing in your search history?"],
  ["solo-tech", "Do you touch yourself differently when you’re stressed out versus when you’re actually turned on?"],
  ["solo-tech", "Have you ever stayed up way too late watching adult content when you had to work early the next morning?"],
  ["solo-tech", "What is a piece of clothing of mine you’ve secretly held or smelled when you were feeling needy?"],
  ["solo-tech", "Do you watch adult content with the sound on high or completely muted?"],
  ["solo-tech", "Have you ever edged yourself to the point of crying or shaking?"],
  ["solo-tech", "What is the quickest you’ve ever brought yourself to climax when you were in a rush?"],
  ["solo-tech", "Have you ever touched yourself in the same room while someone else was sleeping?"],
  ["solo-tech", "Do you prefer watching content that features POV (point of view) or full-body shots?"],
  ["bedroom", "What is one thing I do in bed that turns you off immediately, but you haven't had the heart to tell me?"],
  ["bedroom", "How often do you lie about how close you are to finishing just to match my rhythm?"],
  ["bedroom", "What was the absolute best sexual experience of your entire life, and was it with me?"],
  ["bedroom", "Do you feel like our intimate life is more wild, routine, or adventurous right now?"],
  ["bedroom", "Have you ever wanted to initiate, but held back because you were worried I’d reject you?"],
  ["bedroom", "What is a specific physical position that looks hot, but actually hurts or feels uncomfortable for you?"],
  ["bedroom", "How do you feel about quickies vs. long marathons—which one do you secretly prefer?"],
  ["bedroom", "Is there a scenario where you felt embarrassed by something your body did during intimacy?"],
  ["bedroom", "How do you feel about post-care—do you want to hold each other and cuddle, or do you immediately want space/a shower?"],
  ["bedroom", "What is one boundary you’ve relaxed since we started dating that you used to be strict about?"],
  ["bedroom", "Have you ever felt like you were just \"going through the motions\" during a session with me?"],
  ["bedroom", "What is the highest number of times you’ve ever finished in a single 24-hour period?"],
  ["bedroom", "What is something you’ve seen in a movie or video that you wish we could recreate step-by-step?"],
  ["bedroom", "How do you feel about middle-of-the-night wake-up intimacy?"],
  ["bedroom", "What is one area where you feel I could be much more dominant or confident?"],
  ["risky", "Have you ever had a sudden urge to pull over on the highway or side of the road and do it in the backseat?"],
  ["risky", "How do you feel about making noise when we stay at a hotel or a friend's house?"],
  ["risky", "Have you ever touched me under the table at a restaurant or family dinner?"],
  ["risky", "What is the riskiest place in nature (beach, hiking trail, park) you’d be willing to take your clothes off?"],
  ["risky", "How do you feel about changing room or fitting room hookups?"],
  ["risky", "Have you ever flashed anyone or been flashed in real life?"],
  ["risky", "Do you like the idea of leaving the curtains open slightly at night so people might see shadows?"],
  ["risky", "Have you ever done anything sexual in a public bathroom or airplane lavatory?"],
  ["risky", "What is a public event (concert, cinema, sports game) where you got super turned on out of nowhere?"],
  ["risky", "How do you feel about wearing a tiny piece of string or nothing at all under a fancy dress/suit out to dinner?"],
  ["risky", "Have you ever sent a risky text message while standing right next to the person you sent it to?"],
  ["risky", "What is the closest you’ve ever come to getting caught in the middle of a wild moment?"],
  ["risky", "Do you get a thrill from the idea of someone hearing us through the wall?"],
  ["risky", "Have you ever made out in an ocean or lake where people were swimming nearby?"],
  ["risky", "Would you ever let me take a picture of you during the act if you knew it would never leave my eyes?"],
  ["emotion", "Does physical intimacy make you feel more emotionally attached to me, or are they separate for you?"],
  ["emotion", "What is something I say outside the bedroom that secretly turns you on the most?"],
  ["emotion", "Have you ever cried during or immediately after a climax because of sensory overload?"],
  ["emotion", "How do you feel about eye contact when you are right on the edge of finishing?"],
  ["emotion", "What makes you feel the most physically insecure when your clothes are completely off?"],
  ["emotion", "Have you ever felt vulnerable to the point of panic while trying something new with me?"],
  ["emotion", "What is a praise or word of reassurance you desperately need to hear when we are being intimate?"],
  ["emotion", "Do you prefer lighting to be pitch black, dim warm light, or full daylight?"],
  ["emotion", "What is a mood or emotion (like anger, stress, extreme joy) that makes you want intimacy the most?"],
  ["emotion", "How do you feel about \"make-up sex\" after a heavy argument—does it feel hotter or toxic?"],
  ["emotion", "What is one secret way you signal that you’re in the mood without using words?"],
  ["emotion", "Have you ever felt like you weren't good enough in bed for someone you really cared about?"],
  ["emotion", "What is something about your body’s natural scent that you used to hide, but now accept?"],
  ["emotion", "How do you feel when I look at your body with total intensity—do you feel powerful or exposed?"],
  ["emotion", "What is one thing you need emotionally before you can fully open up physically?"],
  ["wild", "If we were given a free night at a high-end luxury resort with zero rules, what is the first thing we’d do?"],
  ["wild", "How do you feel about food in bed (whipped cream, chocolate syrup, ice, honey)?"],
  ["wild", "Would you ever want to try a massage where we use full body-to-body sliding oil?"],
  ["wild", "How do you feel about shower sex—is it actually hot to you, or just clumsy and slippery?"],
  ["wild", "If you could pick one room in our house to completely renovate into a private pleasure room, which one would it be?"],
  ["wild", "What is a specific piece of clothing you want me to wear during the entire session without taking it off?"],
  ["wild", "How do you feel about morning breath when waking up next to each other with sudden urges?"],
  ["wild", "Would you ever participate in a blindfolded \"guess where I'm touching/kissing you\" challenge?"],
  ["wild", "What is one thing you’ve never allowed anyone else to do to you, but you’d consider letting me try?"],
  ["wild", "If tonight was the absolute last time we could ever be intimate, what exact scenario would you demand we do?"],
];

export const DISCOVER_QUESTIONS: DiscoverQuestion[] = BANK.map(
  ([category, prompt], index) => ({
    id: `disc-${String(index + 1).padStart(3, "0")}`,
    prompt,
    category,
  })
);

export const DISCOVER_QUESTION_COUNT: number = DISCOVER_QUESTIONS.length;

export function discoverQuestionById(id: string): DiscoverQuestion | null {
  return DISCOVER_QUESTIONS.find((row) => row.id === id) ?? null;
}
