import type { ComponentProps } from "react";
import type { Ionicons } from "@expo/vector-icons";

export type FantasyIcon = ComponentProps<typeof Ionicons>["name"];

export type FantasyCategoryId =
  | "oral"
  | "anal"
  | "toys"
  | "film"
  | "group"
  | "power"
  | "impact"
  | "places"
  | "watch"
  | "body";

export type FantasyIdea = {
  id: string;
  title: string;
  category: FantasyCategoryId;
};

export type FantasyCategory = {
  id: FantasyCategoryId;
  label: string;
  tint: string;
  icon: FantasyIcon;
};

export const FANTASY_CATEGORIES: FantasyCategory[] = [
  { id: "oral", label: "Oral", tint: "#FF6B9A", icon: "happy-outline" },
  { id: "anal", label: "Anal", tint: "#C084FC", icon: "flash-outline" },
  { id: "toys", label: "Toys", tint: "#F0A46A", icon: "cube-outline" },
  { id: "film", label: "Film", tint: "#5B8CFF", icon: "videocam-outline" },
  { id: "group", label: "Others", tint: "#FB7185", icon: "people-outline" },
  { id: "power", label: "Power", tint: "#FF5C7A", icon: "lock-closed-outline" },
  { id: "impact", label: "Impact", tint: "#E11D48", icon: "thunderstorm-outline" },
  { id: "places", label: "Places", tint: "#3ECFBF", icon: "location-outline" },
  { id: "watch", label: "Watch", tint: "#E4C37A", icon: "eye-outline" },
  { id: "body", label: "Body", tint: "#F472B6", icon: "heart-outline" },
];

const SHORTS: [string, string, FantasyCategoryId][] = [
  ["oral-f", "Go down on F", "oral"],
  ["oral-m", "Give M a blowjob", "oral"],
  ["oral-69", "Sixty-nine — both mouths at once", "oral"],
  ["oral-facesit", "F sits on M's face", "oral"],
  ["oral-deep-m", "F deep-throats M", "oral"],
  ["oral-slow-m", "Give M a slow, teasing blowjob", "oral"],
  ["oral-fast-f", "Give F fast, hungry oral", "oral"],
  ["oral-morning-m", "Wake M with a blowjob", "oral"],
  ["oral-wake-f", "Wake F by going down on her", "oral"],
  ["oral-wall", "Go down on them against the wall", "oral"],
  ["oral-bed-edge", "Go down on them sitting on the edge of the bed", "oral"],
  ["oral-stand", "Kneel and go down on them while they stand", "oral"],
  ["oral-mirror", "Go down on them in front of the mirror", "oral"],
  ["oral-handsfree-m", "Blow M with no hands", "oral"],
  ["oral-tease", "Tease with your mouth — don't let them finish yet", "oral"],
  ["oral-shower", "Go down on them after a shower", "oral"],
  ["oral-car", "Give head in the car", "oral"],
  ["oral-tv", "Go down on them while they try to watch TV", "oral"],
  ["oral-ice", "Alternate ice and a warm mouth", "oral"],
  ["oral-beg", "Keep going down on them until they beg", "oral"],
  ["oral-swallow", "Swallow when they cum", "oral"],
  ["oral-finish-her-tongue", "M cums on F's tongue", "oral"],
  ["oral-finish-his-tongue", "F cums on M's tongue", "oral"],
  ["oral-vibe-f", "Go down on F with a vibe on her clit", "oral"],
  ["oral-tied-f", "Go down on F while she's tied", "oral"],
  ["oral-tied-m", "Blow M while he's tied", "oral"],
  ["oral-sloppy-m", "Give M a sloppy, messy blowjob", "oral"],
  ["oral-gentle-f", "Give F soft, slow oral", "oral"],
  ["oral-all-night", "Make the whole night just oral", "oral"],
  ["oral-eye-contact", "Go down on them and don't break eye contact", "oral"],
  ["anal-f", "Have anal sex with F", "anal"],
  ["anal-m", "Have anal sex with M", "anal"],
  ["anal-finger-f", "Put a first finger in F's ass", "anal"],
  ["anal-finger-m", "Put a first finger in M's ass", "anal"],
  ["anal-plug-f-sex", "F wears a plug during sex", "anal"],
  ["anal-plug-m-sex", "M wears a plug during sex", "anal"],
  ["anal-behind-f", "Have anal with F from behind", "anal"],
  ["anal-f-on-top", "Have anal with F on top", "anal"],
  ["anal-slow-f", "Have slow anal with F", "anal"],
  ["anal-slow-m", "Have slow anal with M", "anal"],
  ["anal-lube", "Have anal with way too much lube", "anal"],
  ["anal-after-oral", "Oral first, then anal", "anal"],
  ["anal-shower", "Have anal in the shower", "anal"],
  ["anal-tied-f", "Have anal with F while she's tied", "anal"],
  ["anal-tied-m", "Have anal with M while he's tied", "anal"],
  ["anal-strap-m", "F fucks M with a strap-on", "anal"],
  ["anal-strap-f", "Use a strap-on on F", "anal"],
  ["anal-training", "Spend a slow, patient anal training night", "anal"],
  ["anal-only", "Make it an anal-only night — nothing else", "anal"],
  ["anal-toy-first", "Open them with a toy, then anal", "anal"],
  ["anal-rim-f", "Rim F", "anal"],
  ["anal-rim-m", "Rim M", "anal"],
  ["anal-mirror", "Have anal in front of a mirror", "anal"],
  ["anal-then-vag", "Anal first, then vaginal", "anal"],
  ["anal-vag-then", "Vaginal first, then anal", "anal"],
  ["anal-floor", "Have anal on the floor", "anal"],
  ["anal-counter", "Have anal against the kitchen counter", "anal"],
  ["anal-prostate", "Play with M's prostate", "anal"],
  ["anal-talk", "Have anal with filthy talk the whole time", "anal"],
  ["anal-reward", "Give them anal as the reward they earned", "anal"],
  ["toy-f-during", "Use a toy on F during sex", "toys"],
  ["toy-vibe-fuck", "Hold a vibe on F while M fucks her", "toys"],
  ["toy-wand-f", "Use a wand on F until she shakes", "toys"],
  ["toy-dildo-f", "Fuck F with a dildo", "toys"],
  ["toy-rabbit", "Use a rabbit toy on F", "toys"],
  ["toy-sleeve-m", "Stroke M with a sleeve toy", "toys"],
  ["toy-cock-ring", "M wears a cock ring", "toys"],
  ["toy-remote-public", "F wears a remote vibe out in public", "toys"],
  ["toy-remote-dinner", "Use a remote vibe on F at dinner", "toys"],
  ["toy-porn", "Use a toy on them while porn plays", "toys"],
  ["toy-two-f", "Use two toys on F at once", "toys"],
  ["toy-mouth", "Put a toy in F's mouth", "toys"],
  ["toy-tied-f", "Use a toy on F while she's tied", "toys"],
  ["toy-tied-m", "Use a toy on M while he's tied", "toys"],
  ["toy-together", "Share a couple vibe — both of you feel it", "toys"],
  ["toy-prostate-m", "Use a prostate toy on M", "toys"],
  ["toy-beads-f", "Use anal beads on F", "toys"],
  ["toy-beads-m", "Use anal beads on M", "toys"],
  ["toy-race", "Race toys — who cums first", "toys"],
  ["toy-strap-him", "F fucks M with a strap-on", "toys"],
  ["toy-he-only", "M only uses a toy on F — no cock", "toys"],
  ["toy-she-show", "F uses a toy on herself while M watches", "toys"],
  ["toy-he-show", "M uses a toy on himself while F watches", "toys"],
  ["toy-table", "Sneak a toy under the table", "toys"],
  ["toy-bullet", "Hold a bullet vibe on F's clit", "toys"],
  ["toy-glass", "Use a glass toy", "toys"],
  ["toy-app", "Control their toy from your phone", "toys"],
  ["toy-warmup", "Warm them up with a toy before sex", "toys"],
  ["toy-no-hands", "Make them cum with a toy, not your hands", "toys"],
  ["toy-finish", "Finish them with a toy", "toys"],
  ["film-head-f", "Film yourself going down on F", "film"],
  ["film-head-m", "Film F giving M a blowjob", "film"],
  ["film-sex", "Film the two of you having sex", "film"],
  ["film-her-top", "Film F on top", "film"],
  ["film-behind", "Film from behind while you fuck", "film"],
  ["film-close", "Film a close-up of where you join", "film"],
  ["film-mirror", "Film you two in the mirror", "film"],
  ["film-shower", "Film a shower together", "film"],
  ["film-photo-her", "Take photos of F's body", "film"],
  ["film-photo-him", "Take photos of M's body", "film"],
  ["film-voice", "Record a voice note of the night", "film"],
  ["film-replay", "Watch last time's video together, then do it again", "film"],
  ["film-toys", "Film a toy session", "film"],
  ["film-60", "Film only 60 seconds — then stop", "film"],
  ["film-her-face", "Film F's face when she cums", "film"],
  ["film-his-face", "Film M's face when he cums", "film"],
  ["film-tripod", "Set the phone on a tripod and forget it", "film"],
  ["film-one-photo", "Take one photo after you both finish", "film"],
  ["film-polaroid", "Take a Polaroid, then hide it", "film"],
  ["film-strip", "Film them stripping", "film"],
  ["film-hands", "Film only your hands on them", "film"],
  ["film-legs", "Film their legs and feet", "film"],
  ["film-ride", "Film F riding M", "film"],
  ["film-him-down", "Film M going down on F", "film"],
  ["film-quickie", "Film a quickie", "film"],
  ["film-watch-us", "Watch a tape of yourselves", "film"],
  ["film-delete", "Watch it once, then delete it", "film"],
  ["film-keep", "Keep one favourite clip", "film"],
  ["film-lights", "Film with the lights on", "film"],
  ["film-lingerie", "Film F in lingerie", "film"],
  ["group-three", "Have a threesome", "group"],
  ["group-ffm", "Have a threesome with another woman", "group"],
  ["group-mmf", "Have a threesome with another man", "group"],
  ["group-swap", "Swap with another couple", "group"],
  ["group-soft-swap", "Soft swap — kiss and touch the other couple only", "group"],
  ["group-watch-couple", "Watch another couple have sex", "group"],
  ["group-watched", "Let another couple watch you", "group"],
  ["group-same-room", "Swap in the same room", "group"],
  ["group-sep-rooms", "Swap, separate rooms", "group"],
  ["group-mfm", "Two men on F — M plus another", "group"],
  ["group-fmf", "Two women on M — F plus another", "group"],
  ["group-hotwife", "F plays with someone else while M watches", "group"],
  ["group-cuckold", "M watches F get fucked", "group"],
  ["group-she-woman", "F plays with another woman", "group"],
  ["group-he-man", "M plays with another man", "group"],
  ["group-third-watch", "Invite a third just to watch", "group"],
  ["group-third-oral", "Invite a third to join for oral only", "group"],
  ["group-club", "Play in a club playroom", "group"],
  ["group-hotel", "Spend a hotel night with another couple", "group"],
  ["group-text-third", "Text a third together", "group"],
  ["group-pick-photos", "Pick a third from photos, together", "group"],
  ["group-unicorn", "Find a unicorn for one night", "group"],
  ["group-full-swap", "Full swap — sex with the other couple", "group"],
  ["group-kiss-else", "Kiss someone else in front of your partner", "group"],
  ["group-hands-else", "Put your hands on someone else in front of your partner", "group"],
  ["group-she-directs", "F directs M with a third person", "group"],
  ["group-he-directs", "M directs F with a third person", "group"],
  ["group-aftercare-3", "Do aftercare with three of you", "group"],
  ["group-blind-who", "Blindfold them so they don't know whose hands", "group"],
  ["group-fake-third", "Roleplay a third in the room — just the two of you", "group"],
  ["pow-tied", "Tie them up", "power"],
  ["pow-tied-f", "Tie F up", "power"],
  ["pow-tied-m", "Tie M up", "power"],
  ["pow-wrists-bed", "Tie their wrists to the bed", "power"],
  ["pow-spread", "Tie them spread open", "power"],
  ["pow-collar-f", "Put a collar on F", "power"],
  ["pow-collar-m", "Put a collar on M", "power"],
  ["pow-leash-house", "Walk them on a leash around the house", "power"],
  ["pow-gag", "Gag them", "power"],
  ["pow-blindfold", "Blindfold them", "power"],
  ["pow-she-charge", "F is in charge all night", "power"],
  ["pow-he-charge", "M is in charge all night", "power"],
  ["pow-ask-come", "They have to ask permission to cum", "power"],
  ["pow-orgasm-ctrl", "You decide if and when they get to cum", "power"],
  ["pow-edge", "Edge them until they shake", "power"],
  ["pow-beg", "Make them beg for it", "power"],
  ["pow-orders", "Only give orders — they don't get to ask", "power"],
  ["pow-kneel", "Make them kneel", "power"],
  ["pow-all-fours", "Put them on all fours and make them wait", "power"],
  ["pow-hair", "Pull their hair during sex", "power"],
  ["pow-throat", "Hand on their throat — check in, stay safe", "power"],
  ["pow-spank", "Spank them", "power"],
  ["pow-otk", "Pull them over your knee and spank them", "power"],
  ["pow-names", "Call them filthy names they asked for", "power"],
  ["pow-praise", "Talk them through it with praise only — good girl / good boy, no insults", "power"],
  ["pow-service", "They service you first and get nothing until you say", "power"],
  ["pow-tied-tease", "Tie them up and tease them", "power"],
  ["pow-tied-used", "Tie them up and use them", "power"],
  ["pow-free-use", "They're free to use for one hour", "power"],
  ["pow-safeword", "Pick a safeword and practise using it first", "power"],
  ["imp-whipped", "Whip them", "impact"],
  ["imp-crop-f", "Use a riding crop on F", "impact"],
  ["imp-crop-m", "Use a riding crop on M", "impact"],
  ["imp-paddle", "Paddle them", "impact"],
  ["imp-belt", "Give them a light belt spanking", "impact"],
  ["imp-hairbrush", "Spank them with a hairbrush", "impact"],
  ["imp-slap-ass", "Slap their ass", "impact"],
  ["imp-slap-face", "Give a consensual slap across the face", "impact"],
  ["imp-flogged", "Flog them", "impact"],
  ["imp-cane", "Leave cane lines on them", "impact"],
  ["imp-then-sex", "Hit them, then fuck them", "impact"],
  ["imp-then-oral", "Hit them, then go down on them", "impact"],
  ["imp-count", "Make them count every hit out loud", "impact"],
  ["imp-marks", "Leave marks they'll still feel tomorrow", "impact"],
  ["imp-ice", "Put ice on the sting after you hit them", "impact"],
  ["imp-warmup", "Give a warm-up spanking before anything else", "impact"],
  ["imp-harder-moan", "Hit harder every time they moan", "impact"],
  ["imp-harder-quiet", "Hit harder if they stay quiet", "impact"],
  ["imp-thighs", "Spank the insides of their thighs", "impact"],
  ["imp-riding", "Spank them while they ride you", "impact"],
  ["imp-tied", "Hit them while they're tied", "impact"],
  ["imp-she-whips", "F whips M", "impact"],
  ["imp-he-whips", "M whips F", "impact"],
  ["imp-heels-crop", "F wears heels and holds a riding crop", "impact"],
  ["imp-spoon", "Spank them with a wooden spoon", "impact"],
  ["imp-hands", "Spank them with bare hands only", "impact"],
  ["imp-punish", "Spank them as a punishment they asked for", "impact"],
  ["imp-gift", "Spank them as a gift they asked for", "impact"],
  ["imp-oil", "Rub oil into the marks after", "impact"],
  ["imp-mirror", "Show them the marks in the mirror", "impact"],
  ["plc-counter", "Have sex on the kitchen counter", "places"],
  ["plc-shower", "Have sex in the shower", "places"],
  ["plc-wall", "Fuck them against the wall", "places"],
  ["plc-floor", "Have sex on the floor", "places"],
  ["plc-couch", "Have sex on the couch", "places"],
  ["plc-car", "Have sex in the car", "places"],
  ["plc-driveway", "Have sex in the driveway", "places"],
  ["plc-hotel", "Have sex in a hotel room", "places"],
  ["plc-balcony", "Have sex on the balcony", "places"],
  ["plc-woods", "Have sex in the woods", "places"],
  ["plc-beach", "Have sex on the beach at night", "places"],
  ["plc-changing", "Have sex in a changing room", "places"],
  ["plc-cinema", "Fool around in the cinema back row", "places"],
  ["plc-office", "Have sex in the office after hours", "places"],
  ["plc-elevator", "Risk it in an elevator", "places"],
  ["plc-stairs", "Have sex on the stairs", "places"],
  ["plc-alley", "Have a quickie in an alley", "places"],
  ["plc-pool", "Have sex in the pool", "places"],
  ["plc-hottub", "Have sex in the hot tub", "places"],
  ["plc-tent", "Have sex in a tent", "places"],
  ["plc-guest", "Have sex in the guest room", "places"],
  ["plc-window", "Have sex in front of a window", "places"],
  ["plc-washer", "Have sex on the washing machine", "places"],
  ["plc-desk", "Have sex on a desk", "places"],
  ["plc-bar-bath", "Have sex in a bar bathroom", "places"],
  ["plc-lookout", "Have sex parked at a lookout", "places"],
  ["plc-cabin", "Have sex in a cabin", "places"],
  ["plc-plane", "Mile-high fantasy — try it on a plane", "places"],
  ["plc-train", "Have sex in a train toilet", "places"],
  ["plc-roof", "Have sex on a roof or fire escape", "places"],
  ["wat-toy-her", "Watch F use a toy on herself", "watch"],
  ["wat-toy-him", "Watch M use a toy on himself", "watch"],
  ["wat-her-hands", "Watch F touch herself", "watch"],
  ["wat-him-hands", "Watch M touch himself", "watch"],
  ["wat-her-else", "Fantasy: M watches F with someone else", "watch"],
  ["wat-him-else", "Fantasy: F watches M with someone else", "watch"],
  ["wat-mirror", "Do it in front of the mirror the whole time", "watch"],
  ["wat-window", "Leave the window open a crack", "watch"],
  ["wat-lights", "Keep the lights on and look at each other the whole time", "watch"],
  ["wat-she-show", "F puts on a show — M only watches", "watch"],
  ["wat-he-show", "M puts on a show — F only watches", "watch"],
  ["wat-strip", "They do a striptease for you", "watch"],
  ["wat-lap", "They give you a lap dance", "watch"],
  ["wat-porn-us", "Put porn on and have sex to it", "watch"],
  ["wat-porn-her", "Have sex to porn F picked", "watch"],
  ["wat-porn-him", "Have sex to porn M picked", "watch"],
  ["wat-finish", "Watch each other cum", "watch"],
  ["wat-no-touch", "No touching — you only get to watch", "watch"],
  ["wat-doorway", "Watch them from the doorway", "watch"],
  ["wat-catch", "Walk in on them already started", "watch"],
  ["wat-exhibit", "Do it where someone could see", "watch"],
  ["wat-almost", "Get almost caught on purpose", "watch"],
  ["wat-replay-now", "Record it, then watch it immediately", "watch"],
  ["wat-mutual", "Both touch yourselves and watch", "watch"],
  ["wat-she-talks", "F talks M through touching himself", "watch"],
  ["wat-he-talks", "M talks F through touching herself", "watch"],
  ["wat-hotel-mirror", "Watch yourselves in a hotel mirror", "watch"],
  ["wat-dress", "Watch F get dressed after", "watch"],
  ["wat-hard", "Watch M get hard", "watch"],
  ["wat-eyes-come", "Don't look away when they cum", "watch"],
  ["bod-chest-her", "Cum on F's chest", "body"],
  ["bod-face-her", "Cum on F's face", "body"],
  ["bod-chest-him", "Cum on M's chest", "body"],
  ["bod-inside-f", "Cum inside F", "body"],
  ["bod-inside-m", "Cum inside M (anal)", "body"],
  ["bod-creampie", "Creampie — leave it in", "body"],
  ["bod-keep-going", "Creampie, then keep going", "body"],
  ["bod-breasts", "Fuck between F's breasts", "body"],
  ["bod-feet", "Use their feet", "body"],
  ["bod-hair-sex", "Pull their hair while you fuck", "body"],
  ["bod-neck", "Kiss their neck for a long time before anything else", "body"],
  ["bod-bites", "Leave bite marks", "body"],
  ["bod-hickeys", "Leave hickeys", "body"],
  ["bod-scratch-him", "Scratch M's back", "body"],
  ["bod-scratch-her", "Scratch F's back", "body"],
  ["bod-oil", "Oil all over both of you", "body"],
  ["bod-massage", "Massage that turns into sex", "body"],
  ["bod-outer", "Rub on each other — no penetration", "body"],
  ["bod-grind", "Grind clothed until you can't stand it", "body"],
  ["bod-dry", "Dry hump, then strip", "body"],
  ["bod-morning", "Have sex first thing in the morning", "body"],
  ["bod-quickie", "A quickie — in and out", "body"],
  ["bod-marathon", "A long marathon session", "body"],
  ["bod-slow-mean", "Go slow and mean", "body"],
  ["bod-fast-messy", "Go fast and messy", "body"],
  ["bod-stand", "Have sex standing up", "body"],
  ["bod-her-top", "F on top", "body"],
  ["bod-behind", "Fuck them from behind", "body"],
  ["bod-missionary", "Missionary, deep", "body"],
  ["bod-fridge", "Fuck them against the fridge", "body"],
  ["bod-nibble-ear", "Nibble their ear", "body"],
  ["bod-ear-nibbled", "Have your ear nibbled", "body"],
  ["bod-nibble-lip", "Nibble their lower lip", "body"],
  ["bod-lip-nibbled", "Have your lower lip nibbled", "body"],
  ["bod-kiss-behind-ear", "Kiss behind their ear", "body"],
  ["bod-behind-ear-kissed", "Have behind your ear kissed", "body"],
  ["bod-suck-neck", "Suck on their neck", "body"],
  ["bod-neck-sucked", "Have your neck sucked", "body"],
  ["bod-bite-lip", "Bite their lip during a kiss", "body"],
  ["bod-lip-bit", "Have your lip bitten during a kiss", "body"],
  ["bod-tongue-spine", "Run your tongue down their spine", "body"],
  ["bod-spine-tongued", "Have their tongue run down your spine", "body"],
  ["bod-kiss-thigh", "Kiss the inside of their thighs", "body"],
  ["bod-thigh-kissed", "Have the inside of your thighs kissed", "body"],
  ["bod-suck-fingers", "Suck their fingers", "body"],
  ["bod-fingers-sucked", "Have your fingers sucked", "body"],
  ["bod-kiss-stomach", "Kiss down their stomach", "body"],
  ["bod-stomach-kissed", "Have them kiss down your stomach", "body"],
  ["bod-nibble-shoulder", "Nibble their shoulder", "body"],
  ["bod-shoulder-nibbled", "Have your shoulder nibbled", "body"],
  ["bod-bite-ass", "Bite their ass", "body"],
  ["bod-ass-bit", "Have your ass bitten", "body"],
  ["bod-lick-nipples", "Lick their nipples", "body"],
  ["bod-nipples-licked", "Have your nipples licked", "body"],
  ["bod-pinch-nipples", "Pinch their nipples", "body"],
  ["bod-nipples-pinched", "Have your nipples pinched", "body"],
  ["bod-hold-face-kiss", "Hold their face while you kiss", "body"],
  ["bod-face-held-kiss", "Have your face held while they kiss you", "body"],
  ["bod-whisper-filth", "Whisper filthy things in their ear", "body"],
  ["bod-filth-whispered", "Have filthy things whispered in your ear", "body"],
  ["bod-undress-them", "Undress them slowly", "body"],
  ["bod-undressed-slow", "Be undressed slowly", "body"],
  ["bod-touch-clothes", "Touch them through their clothes", "body"],
  ["bod-touched-clothes", "Be touched through your clothes", "body"],
  ["bod-hickeys-got", "Have hickeys left on you", "body"],
  ["bod-bites-got", "Have bite marks left on you", "body"],
  ["bod-neck-long-got", "Have your neck kissed for a long time before anything else", "body"],
  ["bod-hair-fuck-got", "Have your hair pulled while they fuck you", "body"],
  ["bod-feet-on-them", "Use your feet on them", "body"],
  ["bod-feet-used", "Have your feet used", "body"],
  ["bod-scratch-got", "Have your back scratched", "body"],
  ["bod-behind-got", "Be fucked from behind", "body"],
  ["bod-pin-wrists", "Pin their wrists above their head", "body"],
  ["bod-wrists-pinned", "Have your wrists pinned above your head", "body"],
  ["bod-legs-shoulders", "Put their legs over your shoulders", "body"],
  ["bod-legs-shoulders-got", "Have your legs put over their shoulders", "body"],
  ["bod-spit-mouth", "Spit in their mouth", "body"],
  ["bod-spit-got", "Have them spit in your mouth", "body"],
  ["bod-cum-stomach", "Cum on their stomach", "body"],
  ["bod-stomach-came", "Have them cum on your stomach", "body"],
  ["bod-cum-back", "Cum on their back", "body"],
  ["bod-back-came", "Have them cum on your back", "body"],
  ["bod-slap-breasts", "Slap F's breasts", "body"],
  ["bod-breasts-slapped", "Have your breasts slapped", "body"],
  ["bod-eat-creampie", "Eat a creampie out of F", "body"],
  ["bod-creampie-eaten", "Have them eat a creampie out of you", "body"],
  ["bod-kiss-feet", "Kiss their feet", "body"],
  ["bod-feet-kissed", "Have your feet kissed", "body"],
  ["bod-suck-toes", "Suck their toes", "body"],
  ["bod-toes-sucked", "Have your toes sucked", "body"],
  ["oral-under-table", "Go down on them under the table", "oral"],
  ["oral-under-table-got", "Have them go down on you under the table", "oral"],
  ["oral-while-work", "Go down on them while they try to work", "oral"],
  ["oral-while-work-got", "Have them go down on you while you try to work", "oral"],
  ["oral-balls", "Suck M's balls", "oral"],
  ["oral-balls-got", "Have F suck your balls", "oral"],
  ["oral-from-behind", "Go down on them from behind", "oral"],
  ["oral-from-behind-got", "Have them go down on you from behind", "oral"],
  ["oral-hold-head", "Hold their head while they go down on you", "oral"],
  ["oral-head-held", "Have your head held while you go down on them", "oral"],
  ["oral-sit-face", "Sit on their face", "oral"],
  ["oral-face-sat", "Have them sit on your face", "oral"],
  ["oral-wake-you", "Be woken with oral", "oral"],
  ["oral-tease-got", "Have them tease you with their mouth — don't let you finish yet", "oral"],
  ["oral-until-beg-got", "Have them keep going down on you until you beg", "oral"],
  ["oral-swallow-them", "Have them swallow when you cum", "oral"],
  ["oral-cum-mouth", "Cum in their mouth", "oral"],
  ["oral-mouth-came", "Have them cum in your mouth", "oral"],
  ["oral-stand-got", "Have them kneel and go down on you while you stand", "oral"],
  ["oral-wall-got", "Have them go down on you against the wall", "oral"],
  ["oral-shower-got", "Have them go down on you after a shower", "oral"],
  ["oral-car-got", "Have them give you head in the car", "oral"],
  ["oral-eye-got", "Have them go down on you and not break eye contact", "oral"],
  ["oral-tied-you", "Have them go down on you while you're tied", "oral"],
  ["anal-finger-you", "Have a first finger in your ass", "anal"],
  ["anal-rim-got", "Have them rim you", "anal"],
  ["anal-plug-leave", "Put a plug in them and leave it in", "anal"],
  ["anal-plug-left", "Have a plug put in you and left in", "anal"],
  ["anal-prostate-got", "Have your prostate played with", "anal"],
  ["anal-reward-got", "Get anal as the reward you earned", "anal"],
  ["anal-toy-first-got", "Be opened with a toy, then have anal", "anal"],
  ["anal-strap-you-m", "Be fucked by F with a strap-on", "anal"],
  ["anal-strap-you-f", "Have a strap-on used on you (F)", "anal"],
  ["anal-two-fingers", "Use two fingers in their ass", "anal"],
  ["anal-two-fingers-got", "Have two fingers in your ass", "anal"],
  ["anal-hold-cheeks", "Hold their ass open", "anal"],
  ["anal-cheeks-held", "Have your ass held open", "anal"],
  ["toy-you-during", "Have a toy used on you during sex", "toys"],
  ["toy-warmup-got", "Be warmed up with a toy before sex", "toys"],
  ["toy-finish-got", "Be finished with a toy", "toys"],
  ["toy-app-got", "Have them control your toy from their phone", "toys"],
  ["toy-no-hands-got", "Cum from a toy, not their hands", "toys"],
  ["toy-ring-on", "Put a cock ring on M", "toys"],
  ["toy-ring-got", "Have a cock ring put on you", "toys"],
  ["toy-mouth-you", "Have a toy put in your mouth", "toys"],
  ["toy-clamps-on", "Put nipple clamps on them", "toys"],
  ["toy-clamps-got", "Wear nipple clamps", "toys"],
  ["toy-spreader-on", "Use a spreader bar on them", "toys"],
  ["toy-spreader-got", "Be held open with a spreader bar", "toys"],
  ["toy-cage-m", "Lock M in a cock cage", "toys"],
  ["toy-cage-key", "F holds the key to M's cage", "toys"],
  ["toy-wand-you", "Have a wand used on you until you shake", "toys"],
  ["toy-beads-you", "Have anal beads used on you", "toys"],
  ["pow-tied-got", "Be tied up", "power"],
  ["pow-tied-f-got", "Have F tie you up", "power"],
  ["pow-tied-m-got", "Have M tie you up", "power"],
  ["pow-wrists-got", "Have your wrists tied to the bed", "power"],
  ["pow-spread-got", "Be tied spread open", "power"],
  ["pow-collar-you-f", "Wear a collar F puts on you", "power"],
  ["pow-collar-you-m", "Wear a collar M puts on you", "power"],
  ["pow-leash-got", "Be walked on a leash around the house", "power"],
  ["pow-gag-got", "Be gagged", "power"],
  ["pow-blind-got", "Be blindfolded", "power"],
  ["pow-ask-you", "You have to ask permission to cum", "power"],
  ["pow-ctrl-you", "They decide if and when you get to cum", "power"],
  ["pow-edge-got", "Be edged until you shake", "power"],
  ["pow-beg-you", "Beg them for it", "power"],
  ["pow-orders-got", "Only take orders — you don't get to ask", "power"],
  ["pow-kneel-you", "Kneel for them", "power"],
  ["pow-fours-got", "Get on all fours and wait", "power"],
  ["pow-hair-got", "Have your hair pulled during sex", "power"],
  ["pow-throat-got", "Their hand on your throat — check in, stay safe", "power"],
  ["pow-spank-got", "Be spanked", "power"],
  ["pow-otk-got", "Be pulled over their knee and spanked", "power"],
  ["pow-names-got", "Be called filthy names you asked for", "power"],
  ["pow-praise-got", "Be talked through it with praise only", "power"],
  ["pow-service-you", "You service them first and get nothing until they say", "power"],
  ["pow-tease-got", "Be tied up and teased", "power"],
  ["pow-used-got", "Be tied up and used", "power"],
  ["pow-free-you", "You're free to use for one hour", "power"],
  ["pow-crawl", "Make them crawl to you", "power"],
  ["pow-crawl-you", "Crawl to them", "power"],
  ["imp-whip-got", "Be whipped", "impact"],
  ["imp-crop-you", "Have a riding crop used on you", "impact"],
  ["imp-paddle-got", "Be paddled", "impact"],
  ["imp-belt-got", "Receive a light belt spanking", "impact"],
  ["imp-brush-got", "Be spanked with a hairbrush", "impact"],
  ["imp-ass-slapped", "Have your ass slapped", "impact"],
  ["imp-face-slapped", "Receive a consensual slap across the face", "impact"],
  ["imp-flog-got", "Be flogged", "impact"],
  ["imp-cane-got", "Have cane lines left on you", "impact"],
  ["imp-then-sex-got", "Be hit, then fucked", "impact"],
  ["imp-then-oral-got", "Be hit, then have them go down on you", "impact"],
  ["imp-count-you", "Count every hit out loud", "impact"],
  ["imp-marks-you", "Wear marks you'll still feel tomorrow", "impact"],
  ["imp-ice-got", "Have ice put on the sting after they hit you", "impact"],
  ["imp-warmup-got", "Receive a warm-up spanking before anything else", "impact"],
  ["imp-thighs-got", "Be spanked on the insides of your thighs", "impact"],
  ["imp-ride-spank-got", "Be spanked while you ride them", "impact"],
  ["imp-tied-hit-got", "Be hit while you're tied", "impact"],
  ["imp-spoon-got", "Be spanked with a wooden spoon", "impact"],
  ["imp-hands-got", "Be spanked with bare hands only", "impact"],
  ["imp-punish-got", "Be spanked as a punishment you asked for", "impact"],
  ["imp-gift-got", "Be spanked as a gift you asked for", "impact"],
  ["imp-oil-got", "Have oil rubbed into your marks after", "impact"],
  ["imp-mirror-got", "Be shown your marks in the mirror", "impact"],
  ["wat-strip-you", "Do a striptease for them", "watch"],
  ["wat-lap-you", "Give them a lap dance", "watch"],
  ["wat-door-you", "Be watched from the doorway", "watch"],
  ["wat-catch-you", "Be walked in on already started", "watch"],
  ["wat-club-watch", "Watch other people at a sex club", "watch"],
  ["wat-club-watched", "Be watched at a sex club", "watch"],
  ["film-photo-you", "Have photos taken of your body", "film"],
  ["film-nudes-got", "Have nudes taken of you", "film"],
  ["film-send", "Send them a photo while you're apart", "film"],
  ["film-send-got", "Get a photo from them while you're apart", "film"],
  ["plc-bath", "Have sex in the bath", "places"],
  ["plc-closet", "Have sex in a closet", "places"],
  ["plc-work-bath", "Have sex in a work bathroom", "places"],
  ["plc-party-sneak", "Sneak off at a party", "places"],
  ["plc-wedding-sneak", "Sneak off at a wedding", "places"],
  ["plc-park-bench", "Fool around on a park bench at night", "places"],
  ["plc-sauna", "Fool around in a sauna", "places"],
  ["plc-library", "Fool around in a library", "places"],
  ["plc-sex-club", "Visit a sex club together", "places"],
  ["plc-club-dark", "Go into a sex-club dark room", "places"],
  ["plc-glory", "Use a glory hole", "places"],
  ["plc-glory-got", "Be on the receiving side of a glory hole", "places"],
  ["plc-adult-cinema", "Fool around in an adult cinema", "places"],
  ["plc-motel", "Have a cheap motel afternoon", "places"],
  ["group-club-look", "Visit a sex club and only watch", "group"],
  ["group-club-soft", "Soft play at a sex club — touch, no sex", "group"],
  ["group-sex-party", "Go to a sex party", "group"],
  ["group-orgy", "Join an orgy", "group"],
  ["group-kiss-got", "Watch your partner kiss someone else", "group"],
  ["group-hands-got", "Watch your partner put their hands on someone else", "group"],
  ["group-watched-close", "Be watched up close by another couple", "group"],
  ["group-watch-close", "Watch another couple up close", "group"],
  ["group-oral-else", "Go down on someone else in front of your partner", "group"],
  ["group-oral-else-got", "Watch your partner go down on someone else", "group"],
];

export const FANTASY_IDEAS: FantasyIdea[] = SHORTS.map(([id, title, category]) => ({
  id: `fx-${id}`,
  title,
  category,
}));

export function fantasyById(id: string): FantasyIdea | null {
  return FANTASY_IDEAS.find((item) => item.id === id) ?? null;
}

export function fantasyCategoryMeta(id: FantasyCategoryId): FantasyCategory {
  return (
    FANTASY_CATEGORIES.find((item) => item.id === id) ?? FANTASY_CATEGORIES[0]
  );
}

function seededRand(seed: string): () => number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return () => {
    h += 0x6d2b79f5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(items: T[], rand: () => number): T[] {
  for (let i = items.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    const tmp = items[i]!;
    items[i] = items[j]!;
    items[j] = tmp;
  }
  return items;
}

/**
 * One shuffled deck for this couple + user, then leftover cards keep that order.
 * Rebuilding from leftovers with the same seed used to put the same category
 * first after every swipe (ten Toys in a row).
 */
export function leftoverFantasies(
  seenIds: Iterable<string>,
  seed = "deck"
): FantasyIdea[] {
  const seen = new Set(seenIds);
  return shuffledFantasyDeck(`${seed}:v2`).filter((idea) => !seen.has(idea.id));
}

function shuffledFantasyDeck(seed: string): FantasyIdea[] {
  const rand = seededRand(seed);
  const bag = shuffleInPlace([...FANTASY_IDEAS], rand);
  const mixed: FantasyIdea[] = [];
  while (bag.length) {
    const last = mixed[mixed.length - 1]?.category;
    const options = bag
      .map((idea, index) => index)
      .filter((index) => bag[index]!.category !== last);
    const pool = options.length > 0 ? options : bag.map((_, index) => index);
    const pick = pool[Math.floor(rand() * pool.length)]!;
    const [next] = bag.splice(pick, 1);
    mixed.push(next!);
  }
  return mixed;
}

/** Swap only F / M labels for names. Leave he / she / him / his alone so it doesn't read "Ck's face when Ck cums". */
export function personalizeFantasyTitle(
  title: string,
  cast: { f: string; m: string }
): string {
  return title
    .replace(/\bF's\b/g, `${cast.f}'s`)
    .replace(/\bM's\b/g, `${cast.m}'s`)
    .replace(/\bF\b/g, cast.f)
    .replace(/\bM\b/g, cast.m);
}

export function groupFantasiesByCategory(ideas: FantasyIdea[]): {
  category: FantasyCategory;
  items: FantasyIdea[];
}[] {
  return FANTASY_CATEGORIES.map((category) => ({
    category,
    items: ideas.filter((idea) => idea.category === category.id),
  })).filter((row) => row.items.length > 0);
}

/** Deterministic subset of idea ids a demo partner "already liked". */
export function demoLikedFantasyIds(): string[] {
  return FANTASY_IDEAS.filter((_, index) => index % 3 === 0).map(
    (item) => item.id
  );
}
