import { SPICY_DARE_DECK_ID, SPICY_DARE_LEGACY_ID, SPICY_DARES } from "@/lib/spicy-dares";

export type QuestionStatus = "unplayed" | "played";

export type CategoryId =
  | "icebreakers"
  | "deep-reflections"
  | "bedroom-throwbacks"
  | "spicy-dares"
  | "future-dreams"
  | "intimacy-romance"
  | "daily-checkin"
  | "growth-values"
  | "lighthearted"
  | "appreciation"
  | "wildcard";

export type Question = {
  id: string;
  text: string;
  status?: QuestionStatus;
  tags?: string[];
};

export type Category = {
  id: CategoryId;
  name: string;
  iconName: string;
  questions: Question[];
};

function deck(
  id: CategoryId,
  name: string,
  iconName: string,
  prefix: string,
  texts: string[]
): Category {
  return {
    id,
    name,
    iconName,
    questions: texts.map((text, index) => ({
      id: `${prefix}-${index + 1}`,
      text,
      status: "unplayed",
    })),
  };
}

export const LETS_TALK_DECK: Category[] = [
  deck("icebreakers", "Fun & Icebreakers", "sparkles", "ice", [
    "What is a tiny habit of mine you find oddly charming?",
    "If we had to pick a couple nickname that is actually accurate, what is it?",
    "What snack run would you send me on without a list because I already know?",
    "Which of my laughs is your favorite, and when does it come out?",
    "What is a show we pretend we are too cool for but would binge tonight?",
    "If our week had a weather report, what is the forecast?",
    "What is one ridiculous hill you will die on, and why should I join you?",
    "What song should be playing the next time we cook together?",
    "What is a childhood snack you still want in the house?",
    "If we designed a flag for this relationship, what is on it?",
    "What is the most 'us' photo on your phone right now?",
    "Which of my outfits should get a standing ovation more often?",
    "What is a game we would actually finish if we started tonight?",
    "If we swapped morning routines for one day, what would go wrong first?",
    "What is a pet name you want me to try, even as a joke?",
    "What is one thing in this room that would tell a stranger we live here?",
    "If we had a couple sport, what would we be surprisingly good at?",
    "What is a movie we quote that other people do not get?",
    "What should our next lazy Sunday be named?",
    "Which of my impressions needs more stage time?",
    "What is a tiny luxury that makes you feel taken care of?",
    "If we wrote a dating profile as a pair, what is the first line?",
    "What is the last thing that made you snort-laugh?",
    "What is a skill of mine you overestimate on purpose because it is cute?",
    "If we hosted a two-person awards show, what award do I win?",
    "What is a place in town that still feels like a date even if we just grab coffee?",
    "What is one emoji you would assign to me this week?",
    "If we had a secret handshake, what is the last move?",
    "What is a story about us you tell even when I am not in the room?",
    "What should we start collecting just because it is ours?",
    "Which of my texts do you screenshot for later?",
    "What is a silly fear we both have and refuse to admit in public?",
    "If this relationship was a playlist, what is track one?",
    "What is a chore you would bribe me to do with a kiss?",
    "What is the most chaotic snack combination you want us to try?",
    "If we disappeared for four hours with no phones, where do we go?",
    "What is a compliment you want to hear in the middle of a boring errand?",
    "Which of my friends understands us the fastest?",
    "What is a tradition we accidentally started and should keep?",
    "If we had matching tattoos that no one else saw, what would they be?",
    "What is the funniest thing I have ever done while half-asleep?",
    "What should we rename our couch based on how we actually use it?",
    "If we were a sitcom, what is this week's cold open?",
    "What is a dare you would accept from me right now with zero context?",
    "What is one object in our life that deserves a thank-you speech?",
    "Which of my stories do you want me to tell again, slower?",
    "What is a couple rule we should write on a sticky note?",
    "If we opened a tiny shop, what would we sell badly but with love?",
    "What is the last thing I did that made you shake your head and smile?",
    "What is a voice note you wish I would send more often?",
    "If we had a rain check jar, what goes in it first?",
    "What is a look I give you that you can read from across a room?",
    "What should we celebrate this month that nobody else would notice?",
    "If we designed pajamas as a pair, what is printed on them?",
    "What is a question you like being asked even when you already answered it?",
    "What is the most 'main character' version of us on a Friday night?",
    "Which of my playlists is secretly about you?",
    "What is a two-person ritual we could start tomorrow in under five minutes?",
    "If we wrote a postcard to our future selves, what is the joke in the corner?",
    "What is one thing we do that still feels like flirting?"
  ]),
  deck("deep-reflections", "Deep Reflections", "people", "deep", [
    "When did you last feel completely safe with me, and what made it so?",
    "What is a part of you that you still protect, even here?",
    "What does being chosen by me feel like in your body?",
    "What story about yourself are you ready to retire?",
    "When do you feel most like yourself with me?",
    "What is a loneliness you still carry that I cannot see yet?",
    "What do you need from me when you go quiet?",
    "What is a hope you are almost embarrassed to say out loud?",
    "When did you first trust that I would stay?",
    "What does repair look like for you after we miss each other?",
    "What is a family pattern you are trying not to repeat with me?",
    "Where do you still brace for disappointment?",
    "What is something you want me to remember on your hard days?",
    "When do you feel most proud of who we are becoming?",
    "What is a version of you I have not fully met?",
    "What does loyalty mean to you this year, specifically?",
    "When have I surprised you by understanding you without a speech?",
    "What is a fear you want me to hold with you, not fix?",
    "What would it mean to you if we slowed down on purpose?",
    "Where do you still feel like you have to earn love?",
    "What is a truth about us you wish we named more often?",
    "When do you feel most seen in this relationship?",
    "What is a boundary you want celebrated, not negotiated around?",
    "What does home mean when it is a person, not a place?",
    "What is something you forgave me for that still taught you something?",
    "When do you feel furthest from me even if we are in the same room?",
    "What is a dream you paused because life got loud?",
    "What do you want our fights to prove about us, if anything?",
    "When did you last feel proud of how you loved me?",
    "What is a softness you want more permission to have?",
    "What does 'we made it' look like on an ordinary Tuesday?",
    "Where do you want more witness and less advice?",
    "What is a childhood need that still shows up in how you love?",
    "When have I made a hard day lighter without trying to solve it?",
    "What is a risk you took on us that still matters?",
    "What do you want me to protect in you when the world is sharp?",
    "When do you feel most generous in this relationship?",
    "What is a silence between us that is actually peace?",
    "What would you want me to know if words got hard for a while?",
    "Where are you still learning to receive, not just give?",
    "What is a value you will not compromise, even for ease?",
    "When did you last feel like we were on the same side of the table?",
    "What is a grief you want me to keep making space for?",
    "What does devotion look like when nobody is watching?",
    "When do you feel most honest with me?",
    "What is a future conversation you are quietly preparing for?",
    "Where do you want me to be braver with you?",
    "What is a way I can love you that does not look like a grand gesture?",
    "When have we grown and barely noticed until later?",
    "What is a promise you want us to keep even when we are tired?",
    "What does being known by me cost you, and is it worth it?",
    "When do you feel most held without being touched?",
    "What is a story we tell about us that you want to rewrite?",
    "Where do you want more curiosity from me and less assumption?",
    "What is a part of our history you want to honor tonight?",
    "When did you last feel like I chose you in a small, specific way?",
    "What is a hope for us that you have not said because it felt too big?",
    "What do you want to be remembered for in this relationship?",
    "When do you feel most like we are building something, not just surviving?",
    "What is one truth you want on the table before the week gets busy?"
  ]),
  deck("bedroom-throwbacks", "Bedroom Throwbacks", "time-outline", "bt", [
    "What is the first time with me you still replay in high definition?",
    "Which night did we take too long to get to bed, in the best way?",
    "What is a look I gave you that you still feel in your stomach?",
    "When did we last surprise ourselves with how hungry we were for each other?",
    "What outfit of mine should be retired from public and kept for you?",
    "Which room besides the bedroom still has a memory attached?",
    "What is a sound I made that you want on repeat?",
    "When did slow actually beat fast for us?",
    "What is a kiss we started that should have lasted an hour?",
    "Which trip had a night you still use as a measuring stick?",
    "What is something I did with my hands that you think about more than you admit?",
    "When did we laugh in bed and it made everything hotter?",
    "What is a morning-after you wish we could bottle?",
    "Which song in the background accidentally became ours?",
    "What is a position or pace we found by accident and should not lose?",
    "When did I take the lead in a way that still lives in your body?",
    "What is a whispered sentence from a past night you want again?",
    "Which ordinary weekday turned filthy in the best way?",
    "What is a piece of clothing that should come off slower next time, like that night?",
    "When did being quiet make it more intense?",
    "What is a hotel, car, or couch memory that still wins?",
    "Which of my reactions that night do you want to chase again?",
    "What is a time we almost got caught and it made it better?",
    "When did tenderness and heat show up in the same hour?",
    "What is a first we shared that still feels new when you tell it?",
    "Which lighting, time of day, or weather made a night unforgettable?",
    "What is something you did to me that you were proud of afterward?",
    "When did we take our time after, and why did that matter?",
    "What is a text from earlier that day that paid off later?",
    "Which night did eye contact do more than anything else?",
    "What is a move I repeated because you asked without asking?",
    "When did we go from a fight or a long day into something unexpectedly good?",
    "What is a detail — a smell, a fabric, a song — that brings a night back?",
    "Which time did I pay attention in a way that spoiled you?",
    "What is a 'we should do that again' that we actually have not?",
    "When did you feel the most wanted in a specific minute, not a whole night?",
    "What is a tease from the past that still works if I start it now?",
    "Which celebration or ordinary Tuesday still has the better story?",
    "What is a way I said your name that you want back in rotation?",
    "When did we stay in our bodies instead of performing?",
    "What is a late-night or early-morning round you still rank highly?",
    "Which of my insecurities disappeared for a minute because of how I touched you?",
    "What is a time we used the whole room, not just the bed?",
    "When did patience from me feel like a gift, not a delay?",
    "What is a piece of aftercare from a past night you still need?",
    "Which look-back still makes you shift in your seat?",
    "What is a night we rushed that you would restage slower?",
    "When did I follow your lead and it changed the whole temperature?",
    "What is a shared joke from bed that still makes you grin?",
    "Which time did we both arrive at the same want without a speech?",
    "What is a memory that is tender more than it is filthy, and still counts?",
    "When did being a little messy make it more us?",
    "What is a specific kiss placement you want me to find again?",
    "Which night taught us something we still use?",
    "What is a time I asked for what I wanted and it landed?",
    "When did we make space for both of our paces?",
    "What is a throwback you want to recreate this month, not 'someday'?",
    "Which of my sounds, breaths, or words is your favorite souvenir?",
    "What is a night that started vanilla and did not stay there?",
    "When did we feel like beginners again, in a good way?"
  ]),
  {
    id: SPICY_DARE_DECK_ID,
    name: "Spicy Challenges & Dares",
    iconName: "flame",
    questions: SPICY_DARES.map((dare) => ({
      id: dare.id,
      text: dare.text,
      status: dare.status ?? "unplayed",
      tags: [...dare.categories],
    })),
  },
  deck("future-dreams", "Future & Dreams", "compass-outline", "fut", [
    "Where should we be standing a year from now, in a photo nobody posts?",
    "What is a trip we should stop only talking about?",
    "What does a good ordinary decade look like for us?",
    "If we moved, what would we be moving toward, not just away from?",
    "What is a skill you want us to learn together before we get too busy?",
    "How do you want our evenings to feel in five years?",
    "What is a money dream that is actually a freedom dream?",
    "What tradition do you want us to still be doing when we are older?",
    "If we had a shared studio, garage, or kitchen, what gets made there?",
    "What is a city, coast, or quiet town you want to know with me?",
    "How do you want us to handle the next hard season as a pair?",
    "What is a version of success that would still leave room for us?",
    "Who do you want us to become to the people we love?",
    "What is a home detail you already know belongs in our future place?",
    "If we took a month off, how would we spend the third week?",
    "What is a fear about the future you want me to sit with, not swat away?",
    "What should we be braver about planning this year?",
    "How do you want to celebrate a win that is only ours?",
    "What is a ritual for aging that does not sound like a joke?",
    "If we wrote a five-year letter to us, what is the first sentence?",
    "What kind of mornings do you want more of, long-term?",
    "What is a dream you want me to take seriously even if it is inconvenient?",
    "Where do you want more adventure, and where do you want more roots?",
    "What is a boundary we should set now so the future stays kind?",
    "How do you want us to talk about kids, or not kids, without panic?",
    "What is a career or calling shift you can already feel coming?",
    "If we had a shared calendar that only held joy, what is on it?",
    "What does retirement mean to you if it is a feeling, not an age?",
    "What is a place you want to return to until it feels like ours?",
    "How do you want us to show up for each other if one of us gets sick of the grind?",
    "What is a tiny future you want next month, not next decade?",
    "What should we stop postponing because 'later' is getting lazy?",
    "If we designed a weekend cabin in our heads, what is non-negotiable?",
    "How do you want our friends to describe us in ten years?",
    "What is a dream that needs a first ugly step this season?",
    "Where do you want more quiet in the life we are building?",
    "What is a holiday or season you want to claim as ours?",
    "If we had a shared project with a deadline, what would it be?",
    "How do you want to be loved when we are tired of proving things?",
    "What is a map you want on the wall — literal or not?",
    "What does a good fight in the future still include?",
    "If we could give our future selves one tool, what is it?",
    "What is a city at night you want to walk with me with no plan?",
    "How do you want money conversations to feel in two years?",
    "What is a dream you want witnessed even if we never fully do it?",
    "Where should we plant something and wait?",
    "What is a version of 'making it' that still lets us be silly?",
    "If we had a shared plot twist, what would you hope it was?",
    "How do you want us to travel when we have less energy and more taste?",
    "What is a promise about the future that should be small and keepable?",
    "What kind of table do you want us eating at in ten years?",
    "If we wrote a will for our time, who and what gets the best hours?",
    "What is a dream house rule that is actually about how we treat each other?",
    "How do you want to be surprised by me in a year?",
    "What is a future boredom you actually want — the good kind?",
    "If we learned a language, an instrument, or a craft, which one and why?",
    "What should we protect from other people's timelines?",
    "How do you want us to talk about aging bodies with respect and heat?",
    "What is a horizon you want me to keep pointing at when you forget?",
    "If this year had a title in our story, what do you want it to be?"
  ]),
  deck("intimacy-romance", "Intimacy & Romance", "heart", "ir", [
    "What is a romantic gesture that actually works on you, not the movie version?",
    "When do you feel most courted by me in regular life?",
    "What kind of kiss do you want at the door tonight?",
    "Where do you want my hand when we are walking?",
    "What is a way I can flirt with you in a grocery aisle?",
    "What does a slow evening look like when sex is not the assignment?",
    "What is a compliment about your body you want to hear without a punchline?",
    "How do you want to be held when you are not sad, just here?",
    "What is a date we could pull off without leaving the block?",
    "What song should I put on if I want you to come closer?",
    "What is a text you want to get in the middle of a workday?",
    "How do you like to be looked at across a table?",
    "What is a piece of care that feels more intimate than a gift?",
    "When do you want more words, and when do you want more presence?",
    "What is a way I can dress for you without making a whole production?",
    "What does 'come here' mean in our language?",
    "What is a scent, a fabric, or a light that makes you feel romantic?",
    "How do you want me to start a night that is about us, not logistics?",
    "What is a small yes you want more often — a touch, a note, a pause?",
    "Where on you should I kiss that is not a prelude?",
    "What is a way to dance in the kitchen that does not feel ironic?",
    "How do you want to be woken up on a good morning?",
    "What is a ritual for coming back together after we have been in our heads?",
    "What kind of eye contact still undoes you?",
    "What is a love letter sentence you wish I would just say?",
    "How do you want me to sit with you on the couch if I am trying to be close?",
    "What is a flower, a food, or a nothing-special thing that still reads as romance?",
    "When does teasing feel loving, and when does it miss?",
    "What is a way I can take your phone out of your hand kindly?",
    "How do you want to be greeted after a long day?",
    "What is an intimate question you like being asked even if the answer is 'not now'?",
    "What does exclusivity feel like as a practice, not a rule?",
    "What is a way we can be in public that still feels like a secret?",
    "How do you want me to remember the details you drop once?",
    "What is a bath, a walk, or a drive that would count as a date?",
    "When do you want me to initiate closeness without checking the mood first?",
    "What is a way to say 'I missed you' that is not a paragraph?",
    "How do you want your hair, your face, your hands treated when I am close?",
    "What is a romantic risk you want me to take this week?",
    "What does safety in romance look like for your nervous system?",
    "What is a playlist, a candle, or a clean sheet that still matters?",
    "How do you want me to talk about you when you can overhear?",
    "What is a way to celebrate a regular Wednesday?",
    "When do you want more heat, and when do you want more hush?",
    "What is a touch on the back of the neck or the wrist that you want more of?",
    "How do you want to fall asleep if we are doing it on purpose?",
    "What is a 'just because' you still notice?",
    "What does being adored look like without being put on a pedestal?",
    "How do you want me to handle your body on a low-confidence day?",
    "What is a shared look we should practice until it is a reflex?",
    "When is silence intimate, and when is it distance?",
    "What is a way I can plan something and still leave room for you?",
    "How do you want to be asked 'can I kiss you' even though I already can?",
    "What is a romance you want that has nothing to do with anniversaries?",
    "What kind of patience from me feels like love?",
    "How do you want me to show pride in you without making a speech?",
    "What is a way to end a night that makes tomorrow easier?",
    "When do you feel most beautiful with me, and what is happening?",
    "What is a closeness you want that we keep skipping because we are competent at life?",
    "If romance had a temperature tonight, what do you want it set to?"
  ]),
  deck("daily-checkin", "Daily Connection", "sunny-outline", "dc", [
    "What is taking up the most space in your head today?",
    "Where did your energy go this morning?",
    "What is one thing you need from me before tonight gets loud?",
    "What would make the next three hours 10% easier?",
    "What is a win from today that is too small to post?",
    "Where are you tender, and where are you fine?",
    "What is a body signal you noticed and almost ignored?",
    "Who or what drained you, without a full debrief?",
    "What is something you are looking forward to in the next 24 hours?",
    "If tonight had a job, what is it: rest, talk, play, or nothing?",
    "What is a worry you can set down if I hold it for an hour?",
    "What did you eat, skip, or crave that tells a story?",
    "Where do you want quiet, and where do you want company?",
    "What is a message you received today that stuck?",
    "How is your patience with the world right now, one to ten?",
    "What is a kindness you want to give yourself this evening?",
    "What should we not talk about tonight, on purpose?",
    "What should we definitely talk about before we sleep?",
    "What is a task hanging over you that I could take or share?",
    "How connected do you feel to me in this exact minute?",
    "What is a mood you brought home that is not about me?",
    "What would a perfect next hour look like, realistically?",
    "Where did you laugh today, even a little?",
    "What is a no you said, or wish you had said?",
    "What is a yes you want to give me tonight that is small?",
    "How is your sleep debt, honestly?",
    "What is a hope for tomorrow you can name in one sentence?",
    "Where do you want a hand on you while we talk?",
    "What is something you are proud of from this week so far?",
    "What is something you are avoiding that I should know exists?",
    "If your day was a color, what is it, and is it fading or getting louder?",
    "What do you need more of: food, water, air, or me shutting up for a bit?",
    "What is a song, a scroll, or a scene that affected you today?",
    "How do you want to be greeted when I see you next?",
    "What is a boundary you used today that I should respect tonight?",
    "Where are you at with wanting touch, from 'not now' to 'please'?",
    "What is a tiny plan we can keep that would make you feel considered?",
    "What is taking longer than it should in your world right now?",
    "Who do you need to be for the rest of the day, and who do you want to be with me?",
    "What is a thought you keep looping?",
    "What would help you land in this room?",
    "What is a gratitude from today that is not about productivity?",
    "How can I make the evening less like a second shift?",
    "What is a question you wish someone had asked you at work or out there?",
    "What is your social battery, and do you need to hide or be witnessed?",
    "What is a body comfort you want: shower, stretch, snack, bed?",
    "If we only had ten honest minutes, what is the headline?",
    "What is a way I can check on you later without hovering?",
    "What are you pretending is fine?",
    "What is a delight you noticed that you almost did not mention?",
    "How do you want the lights, the sound, the pace of this room?",
    "What is a tomorrow-morning need I can help set up tonight?",
    "Where did you feel competent today?",
    "Where did you feel small today?",
    "What is a joke from your day that needs an audience of one?",
    "What should we eat, skip, or order so the night stays kind?",
    "What is a feeling sitting in your chest with no name yet?",
    "How can we make tonight a closed loop, not an open tab?",
    "What is one sentence you want me to remember until breakfast?",
    "If we rated this day together, what would you want my rating to include?"
  ]),
  deck("growth-values", "Growth & Values", "trending-up-outline", "gv", [
    "What value of yours did I get to see in action this month?",
    "Where are you growing in a way that is uncomfortable but true?",
    "What is a money value we should say out loud so it stops being a vibe?",
    "How do you want us to handle anger so it does not go to waste?",
    "What is a family expectation you are done carrying into this relationship?",
    "Where do you want more courage from me as a partner?",
    "What does fairness look like in our week, not in a debate?",
    "What is a belief you changed because of us?",
    "How do you want to be challenged without feeling attacked?",
    "What is a line you will not cross, even if it would be easier?",
    "Where are we too comfortable, and is that peace or a rut?",
    "What does ambition look like when it still leaves room for this?",
    "How do you want us to talk about religion, meaning, or none of it?",
    "What is a way we treat other people that you want us to keep?",
    "What is a way we treat other people that you want us to stop?",
    "Where do you need more honesty from me even if it is clumsy?",
    "What is a growth edge you want witnessed, not fixed?",
    "How should we decide when we disagree and both care a lot?",
    "What is a value around time that we keep violating?",
    "What does loyalty look like when we are apart?",
    "Where do you want more independence without it feeling like a withdrawal?",
    "What is a lesson from a past relationship you still use well?",
    "What is a lesson from a past relationship you are ready to retire?",
    "How do you want us to repair after we miss each other?",
    "What does respect sound like in a tense conversation?",
    "Where are you becoming someone you actually like?",
    "What is a community, friendship, or family tie you want us to invest in?",
    "How do you want us to think about health as a shared value?",
    "What is a 'we do not do that here' rule worth writing down?",
    "Where do you want more play in how we grow, not just work?",
    "What is a political or social value that actually shapes your days?",
    "How should we handle jealousy if it shows up, without shame spirals?",
    "What does generosity look like when we are not flush?",
    "Where do you want me to hold you accountable kindly?",
    "What is a dream of yours that would require me to stretch?",
    "How do you want us to talk about therapy, tools, or getting help?",
    "What is a pride you have about how we fight now versus before?",
    "Where do you still perform, and what would dropping it cost?",
    "What is a value around sex and consent you want refreshed, not assumed?",
    "How do you want us to treat mistakes: ours and each other's?",
    "What does 'enough' mean for you this year?",
    "Where are you learning to receive care instead of earning it?",
    "What is a cultural or family tradition you want to keep, remix, or skip?",
    "How should we celebrate growth that is invisible to other people?",
    "What is a hard conversation we are grown enough for now?",
    "Where do you want more curiosity about who I am becoming?",
    "What does partnership mean on a boring administrative day?",
    "How do you want us to treat each other's work, art, or grind?",
    "What is a fear-based rule you want to replace with a value-based one?",
    "Where did we get better at repair this year?",
    "What is a way I can support a change you are already making?",
    "How do you want to be a person in the world with me beside you?",
    "What is a legacy feeling, not a legacy object, you want us to leave?",
    "Where do you want more humility in how we love?",
    "What does justice look like inside a two-person household?",
    "How should we handle advice from people who do not live our life?",
    "What is a growth you want credit for that I have under-noticed?",
    "Where are we aligned, and where are we just avoiding the map?",
    "What is a value you want on the fridge, not in a speech?",
    "If we wrote a couple manifesto in five lines, what is line one?"
  ]),
  deck("lighthearted", "Would You Rather & Debates", "help-circle-outline", "wyr", [
    "Would you rather have a perfect Saturday in or a chaotic Saturday out?",
    "Would you rather always cook together or always eat out, no in-between?",
    "Would you rather relive our best trip or book a mystery one with one clue?",
    "Would you rather I plan every date for a month or you plan every date?",
    "Would you rather talk for an hour in the dark or walk for an hour in the cold?",
    "Would you rather share a dessert or guard your own like a dragon?",
    "Would you rather have a surprise party or a surprise getaway?",
    "Would you rather never use a phone in bed or never use a phone at dinner?",
    "Would you rather be slightly too hot in a room or slightly too cold?",
    "Would you rather I pick the movie forever or you pick the music forever?",
    "Would you rather have a kitchen that always looks nice or a kitchen that always has snacks?",
    "Would you rather get caught in the rain or get stuck in an airport together?",
    "Would you rather have more mornings or more midnights as a pair?",
    "Would you rather I roast you lovingly or praise you constantly?",
    "Would you rather live by the water or in a city that never shuts up?",
    "Would you rather have a standing Friday date or a floating 'when we feel it' date?",
    "Would you rather I learn your coffee order perfectly or your playlist perfectly?",
    "Would you rather skip gifts or skip big holiday productions?",
    "Would you rather have a dog energy weekend or a cat energy weekend, regardless of pets?",
    "Would you rather argue about directions or argue about the thermostat?",
    "Would you rather have a secret language or a secret handshake?",
    "Would you rather I write you letters or I take more photos of us?",
    "Would you rather eat the same breakfast for a year or never repeat a dinner?",
    "Would you rather have a balcony or a bathtub as the non-negotiable?",
    "Would you rather be overdressed together or underdressed together?",
    "Would you rather have a long drive with a good talk or a short flight with a good nap?",
    "Would you rather I start the flirting or you start the flirting, as a default?",
    "Would you rather host once a month or never host and always go out?",
    "Would you rather have matching mugs or matching keys?",
    "Would you rather spend a windfall on time off or on a thing we keep?",
    "Would you rather I tell you the truth immediately or wait until I have the kind version?",
    "Would you rather have a house full of plants or a house full of books?",
    "Would you rather dance badly in public or sing badly in the car with the windows down?",
    "Would you rather have a perfect first hour of the day or a perfect last hour?",
    "Would you rather I handle the social calendar or you handle it and I just show up?",
    "Would you rather have a cabin weekend with no wifi or a hotel weekend with a ridiculous robe?",
    "Would you rather replay a favorite meal or try the new place that might be mid?",
    "Would you rather I be five minutes early forever or fashionably late with coffee in hand?",
    "Would you rather have a standing joke we never explain or a standing toast we always do?",
    "Would you rather fight in person the same day or sleep and talk in the morning?",
    "Would you rather have more tattoos as a story or more stamps in a passport?",
    "Would you rather I pick your clothes for a night out or you pick mine?",
    "Would you rather have a quiet anniversary or an over-the-top one?",
    "Would you rather be known as the funny couple or the intense couple?",
    "Would you rather have a shared hobby we are bad at or separate hobbies we brag about?",
    "Would you rather I text you all day or save it and be fully here at night?",
    "Would you rather have pancakes at midnight or pizza at breakfast?",
    "Would you rather win a petty debate or be right later in private?",
    "Would you rather have a porch with people or a porch with nobody?",
    "Would you rather I remember dates or I remember how you take comfort?",
    "Would you rather get lost on purpose or have a tight itinerary with room for gelato?",
    "Would you rather have a signature cocktail or a signature walk?",
    "Would you rather I be extra in public or extra when it is only us?",
    "Would you rather have a redo of a awkward first or a sequel to a great third date?",
    "Would you rather the house smell like dinner or like clean sheets?",
    "Would you rather have one epic vacation or four small escapes?",
    "Would you rather I learn a skill for you or teach you a skill I love?",
    "Would you rather have a rain day with movies or a sun day with nowhere to be?",
    "Would you rather I ask more questions or tell more stories?",
    "Would you rather we be legendary at hosting breakfast or legendary at leaving a party at the right time?"
  ]),
  deck("appreciation", "Gratitude & Praise", "happy-outline", "gp", [
    "What is a small thing I do that you notice every time?",
    "When did I make an ordinary day feel chosen?",
    "What is a way I love you that I probably think is invisible?",
    "What is a strength of mine you borrowed this month?",
    "How did I show up for you when it was inconvenient?",
    "What is a look, a text, or a habit of mine you would miss immediately?",
    "What is something I cooked, fixed, or handled that you still feel?",
    "When did my patience with you actually land?",
    "What is a way I am gentle that you do not want me to toughen up?",
    "What is a way I am fierce that you do not want me to soften?",
    "What is a recent apology, repair, or try from me that you appreciated?",
    "How do I make this place feel like ours?",
    "What is a talent of mine you want more stage time for?",
    "When did I make you laugh at the exact right second?",
    "What is a body, style, or presence compliment you want without being shy about it?",
    "What is a decision I made that took weight off you?",
    "How do I love you in a language you actually receive?",
    "What is a time I remembered a detail and it mattered more than the gift?",
    "What is a way I am becoming someone you like watching grow?",
    "When did I protect our time without making a speech?",
    "What is a quiet competence of mine that turns you on or calms you down?",
    "How did I make you feel proud to be with me, specifically?",
    "What is a kindness I showed someone else that made you feel closer to me?",
    "What is a hard thing I did that you want named as brave?",
    "When did I listen all the way to the end?",
    "What is a way I touch you that always reads as care?",
    "What is something about my mind you are grateful for this week?",
    "How do I make mornings or nights easier without you asking?",
    "What is a risk I took on us that you still respect?",
    "When did I make you feel attractive without a setup?",
    "What is a tradition I keep that you would be sad to lose?",
    "How do I handle your bad day in a way that actually helps?",
    "What is a piece of my humor that is only for you?",
    "What is a way I am reliable that you do not want to take for granted?",
    "When did I choose us over being right?",
    "What is a skill in bed or in the kitchen or in a crisis you want praised plainly?",
    "How do I make you feel safe enough to be embarrassing?",
    "What is a recent 'I see you' from me that stuck?",
    "What is a way I spend money, time, or attention that feels like love?",
    "When did I make the house, the car, or the calendar kinder?",
    "What is a part of my personality you would keep in a fire?",
    "How do I celebrate you in a way that does not miss?",
    "What is a growth I made that you noticed before I did?",
    "When did I make you feel wanted on a regular afternoon?",
    "What is a way I say your name, or say us, that you like?",
    "How do I repair in a way you trust?",
    "What is a silly thing I do that still counts as devotion?",
    "When did I make space for your people, your work, or your weirdness?",
    "What is a sensory thing about me — voice, smell, hands — you are grateful for?",
    "How do I make you feel like a team on errands?",
    "What is a promise I kept that was small and therefore huge?",
    "When did I make you feel chosen in front of other people, the right amount?",
    "What is a way I am still curious about you?",
    "How do I love you when I am tired, and why does that matter?",
    "What is a compliment you want me to hear about myself from you?",
    "When did I make a hard conversation possible?",
    "What is a piece of our history I honor well?",
    "How do I make play feel allowed?",
    "What is a way I have loved you that you want more of, not less?",
    "If you had to thank me for one thing from this month, what is it?"
  ]),
  deck("wildcard", "Wildcard & Spontaneous", "flash-outline", "wc", [
    "If we left the house in ten minutes with no plan, where do we point the car?",
    "What is a yes you would give me right now if I asked for something small and weird?",
    "Pick a room. What is the most alive thing we could do in it tonight?",
    "What is a text you want me to send you in an hour that would change the temperature?",
    "If we swapped phones for two minutes, what would you hope I notice?",
    "What is a dare you would accept if it stayed between us?",
    "Name a street, a park, or a parking lot that should get a story tonight.",
    "What is a song we should put on and not talk until it ends?",
    "If we had to make a mess of the kitchen or the bed, which wins?",
    "What is a costume, a hat, or a shirt of mine that should come out as a joke with intent?",
    "Give me a two-word instruction for the rest of the evening.",
    "What is a coin-flip decision we should actually let a coin make?",
    "If we wrote a note and left it for later, what does it say?",
    "What is a place we have walked past a hundred times and never gone in?",
    "Start a sentence with 'Meet me' and finish it.",
    "What is a 20-minute adventure that requires shoes?",
    "What is a 20-minute adventure that requires no shoes?",
    "If we turned off one light in the house, which one changes the mood most?",
    "What is a flavor, a drink, or a snack we should hunt down tonight?",
    "Pick a number between 1 and 10. That is how extra we go. What happens at that number?",
    "What is a photo we should take that we would never post?",
    "If we had to compliment a stranger as a team, where would we be brave?",
    "What is a rule of the house we should break once, kindly?",
    "Give me a scavenger hunt item in this room that leads to you.",
    "What is a voice memo you want to record and not play until tomorrow?",
    "If we danced for one song, where do we stand?",
    "What is a window, a rooftop, or a stoop that needs us on it?",
    "Pick a time tomorrow. What do we do at that time that is not useful?",
    "What is a 'pull over' fantasy that is actually a five-minute reality?",
    "If we packed a bag with three things and left, what are the three things?",
    "What is a rumor we should start about our night that is only half true?",
    "Give me a word. I have to use it before we sleep. What is it?",
    "What is a mirror moment we should actually do, not joke about?",
    "If we ordered something we never order, what is it?",
    "What is a stretch, a shower, or a walk that should include both of us?",
    "Pick a piece of furniture. It is now the main character. Why?",
    "What is a childhood yes we can do a grown version of tonight?",
    "If we had a plot twist at 9 p.m., what would you want it to be?",
    "What is a question you want me to ask you in a different room?",
    "Give me a countdown from five. What happens at one?",
    "What is a 'we would never' that we might, if the night got loose?",
    "If we wrote our names somewhere they do not belong, where?",
    "What is a silent activity that would still feel like a date?",
    "Pick an hour this weekend that is now a secret appointment. What is it for?",
    "What is a dare involving the porch, the hallway, or the last light off?",
    "If we had to make a toast with whatever is in the fridge, what are we toasting?",
    "What is a way to arrive home like we are arriving at a hotel?",
    "Give me a color. The next thing we do has to include it.",
    "What is a map pin within 30 minutes we have no good reason to visit, so we should?",
    "If we swapped who leads the next hour, what is your first move?",
    "What is a sentence you want whispered at a random time tonight?",
    "Pick a household object. It is now a prop. How?",
    "What is a 'stay up too late' reason that would be worth it?",
    "If we had a safe word for boredom, and someone said it, what do we do?",
    "What is a door we should close, or open, on purpose?",
    "Give me a place to kiss you that is not the usual commute.",
    "What is a 12-minute plan that would make this night unrepeatable?",
    "If the night needed a title, and we had to earn it, what title do you want?",
    "What is a wildcard you have been saving that is finally in season?",
    "Say the first honest impulse you have for the next hour. We will treat it as a lead."
  ]),
];

export function categoryById(id: string): Category {
  const resolved = id === SPICY_DARE_LEGACY_ID ? SPICY_DARE_DECK_ID : id;
  const category = LETS_TALK_DECK.find((row) => row.id === resolved);
  if (!category) {
    throw new Error(`Unknown Let's Talk category: ${id}`);
  }
  return category;
}

export function questionCount(): number {
  return LETS_TALK_DECK.reduce((sum, category) => sum + category.questions.length, 0);
}
