#!/usr/bin/env node
/**
 * Regenerates supabase/seed.sql from the Get Spicy JSON decks.
 * Run: npm run seed
 */
const fs = require("fs");
const path = require("path");

const files = [
  "pre-foreplay.json",
  "pre-foreplay-2.json",
  "foreplay.json",
  "foreplay-2.json",
  "step-it-up.json",
  "step-it-up-2.json",
  "finish-off.json",
  "finish-off-2.json",
  "afterglow.json",
];

const cardsDir = path.join(__dirname, "..", "games", "get-spicy", "cards");
const cards = files.flatMap((file) =>
  JSON.parse(fs.readFileSync(path.join(cardsDir, file), "utf8"))
);

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

const values = cards
  .map(
    (card) =>
      `  (${sqlString(card.category)}, ${sqlString(card.title)}, ${sqlString(card.body ?? card.description)}, true, true, ${card.order})`
  )
  .join(",\n");

const sql = `-- Global default Get Spicy decks (couple_id is null).
-- Regenerated by \`npm run seed\` from games/get-spicy/cards/*.json

insert into public.cards (stage, title, body, is_default, is_active, sort_order)
values
${values};
`;

const out = path.join(__dirname, "..", "supabase", "seed.sql");
fs.writeFileSync(out, sql);
console.log(`Wrote ${cards.length} cards to supabase/seed.sql`);
